-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [tls_codec]: external functions.
-- This is a template file: hax seeded TlsCodec/Assumptions/FunsExternal.lean
-- from it, and that copy is yours to fill in. This file is regenerated on
-- every extraction; diff it against your Assumptions file to see what the
-- extraction now requires.
import Aeneas
import CoreModels
import TlsCodec.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open tls_codec

/-- [tls_codec::{impl core::fmt::Debug for tls_codec::Error}::fmt]:
    Source: 'tls_codec/src/lib.rs', lines 74:9-74:14
    Visibility: public -/
axiom Error.Insts.CoreFmtDebug.fmt
  :
  Error → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::{impl core::fmt::Display for tls_codec::Error}::fmt]:
    Source: 'tls_codec/src/lib.rs', lines 112:4-114:5
    Visibility: public -/
axiom Error.Insts.CoreFmtDisplay.fmt
  :
  Error → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::{impl core::fmt::Debug for tls_codec::U24}::fmt]:
    Source: 'tls_codec/src/lib.rs', lines 385:22-385:27
    Visibility: public -/
axiom U24.Insts.CoreFmtDebug.fmt
  :
  U24 → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for alloc::boxed::Box<T>}::tls_deserialize_bytes]:
    Source: 'tls_codec/src/primitives.rs', lines 493:4-495:5
    Visibility: public -/
axiom Box.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes
  {T : Type} (DeserializeBytesInst : DeserializeBytes T) :
  Slice Std.U8 → RustM (core.result.Result (T × (Slice Std.U8)) Error)

/-- [tls_codec::quic_vec::{impl tls_codec::SerializeBytes for &'_0 [T]}::tls_serialize_bytes]:
    Source: 'tls_codec/src/quic_vec.rs', lines 211:4-245:5
    Visibility: public -/
axiom Shared0Slice.Insts.Tls_codecSerializeBytes.tls_serialize_bytes
  {T : Type} (SerializeBytesInst : SerializeBytes T) :
  Slice T → RustM (core.result.Result (alloc.vec.Vec Std.U8) Error)

/-- [tls_codec::quic_vec::write_hex]:
    Source: 'tls_codec/src/quic_vec.rs', lines 286:0-297:1 -/
axiom quic_vec.write_hex
  :
  core.fmt.Formatter → Slice Std.U8 → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::quic_vec::{impl core::fmt::Debug for tls_codec::quic_vec::VLBytes}::fmt]:
    Source: 'tls_codec/src/quic_vec.rs', lines 302:12-306:13
    Visibility: public -/
axiom quic_vec.VLBytes.Insts.CoreFmtDebug.fmt
  :
  quic_vec.VLBytes → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::quic_vec::{impl core::fmt::Debug for tls_codec::quic_vec::VLByteVec}::fmt]:
    Source: 'tls_codec/src/quic_vec.rs', lines 302:12-306:13
    Visibility: public -/
axiom quic_vec.VLByteVec.Insts.CoreFmtDebug.fmt
  :
  quic_vec.VLByteVec → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::quic_vec::{impl core::fmt::Debug for tls_codec::quic_vec::VLByteSlice<'_0>}::fmt]:
    Source: 'tls_codec/src/quic_vec.rs', lines 664:4-668:5
    Visibility: public -/
axiom quic_vec.VLByteSlice.Insts.CoreFmtDebug.fmt
  :
  quic_vec.VLByteSlice → core.fmt.Formatter → RustM ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU8}::get_content_lengths]:
    Source: 'tls_codec/src/tls_vec.rs', lines 250:12-273:13 -/
axiom tls_vec.TlsByteVecU8.get_content_lengths
  :
  tls_vec.TlsByteVecU8 → RustM (core.result.Result (Std.Usize × Std.Usize)
    Error)

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU16}::get_content_lengths]:
    Source: 'tls_codec/src/tls_vec.rs', lines 250:12-273:13 -/
axiom tls_vec.TlsByteVecU16.get_content_lengths
  :
  tls_vec.TlsByteVecU16 → RustM (core.result.Result (Std.Usize × Std.Usize)
    Error)

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU24}::get_content_lengths]:
    Source: 'tls_codec/src/tls_vec.rs', lines 250:12-273:13 -/
axiom tls_vec.TlsByteVecU24.get_content_lengths
  :
  tls_vec.TlsByteVecU24 → RustM (core.result.Result (Std.Usize × Std.Usize)
    Error)

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU32}::get_content_lengths]:
    Source: 'tls_codec/src/tls_vec.rs', lines 250:12-273:13 -/
axiom tls_vec.TlsByteVecU32.get_content_lengths
  :
  tls_vec.TlsByteVecU32 → RustM (core.result.Result (Std.Usize × Std.Usize)
    Error)

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::TlsVecU8<T>}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 548:21-548:26
    Visibility: public -/
axiom tls_vec.TlsVecU8.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) :
  tls_vec.TlsVecU8 T → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::TlsVecU16<T>}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 548:21-548:26
    Visibility: public -/
axiom tls_vec.TlsVecU16.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) :
  tls_vec.TlsVecU16 T → core.fmt.Formatter → RustM ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::TlsVecU24<T>}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 548:21-548:26
    Visibility: public -/
axiom tls_vec.TlsVecU24.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) :
  tls_vec.TlsVecU24 T → core.fmt.Formatter → RustM ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::TlsVecU32<T>}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 548:21-548:26
    Visibility: public -/
axiom tls_vec.TlsVecU32.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) :
  tls_vec.TlsVecU32 T → core.fmt.Formatter → RustM ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::SecretTlsVecU8<T>}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 548:21-548:26
    Visibility: public -/
axiom tls_vec.SecretTlsVecU8.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) (zeroizeZeroizeInst :
  zeroize.Zeroize T) :
  tls_vec.SecretTlsVecU8 T → core.fmt.Formatter → RustM
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter ×
    (core.fmt.Formatter → core.fmt.Formatter))

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::SecretTlsVecU16<T>}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 548:21-548:26
    Visibility: public -/
axiom tls_vec.SecretTlsVecU16.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) (zeroizeZeroizeInst :
  zeroize.Zeroize T) :
  tls_vec.SecretTlsVecU16 T → core.fmt.Formatter → RustM
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter ×
    (core.fmt.Formatter → core.fmt.Formatter))

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::SecretTlsVecU24<T>}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 548:21-548:26
    Visibility: public -/
axiom tls_vec.SecretTlsVecU24.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) (zeroizeZeroizeInst :
  zeroize.Zeroize T) :
  tls_vec.SecretTlsVecU24 T → core.fmt.Formatter → RustM
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter ×
    (core.fmt.Formatter → core.fmt.Formatter))

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::SecretTlsVecU32<T>}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 548:21-548:26
    Visibility: public -/
axiom tls_vec.SecretTlsVecU32.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) (zeroizeZeroizeInst :
  zeroize.Zeroize T) :
  tls_vec.SecretTlsVecU32 T → core.fmt.Formatter → RustM
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter ×
    (core.fmt.Formatter → core.fmt.Formatter))

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::TlsByteVecU8}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 754:28-754:33
    Visibility: public -/
axiom tls_vec.TlsByteVecU8.Insts.CoreFmtDebug.fmt
  :
  tls_vec.TlsByteVecU8 → core.fmt.Formatter → RustM ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::TlsByteVecU16}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 754:28-754:33
    Visibility: public -/
axiom tls_vec.TlsByteVecU16.Insts.CoreFmtDebug.fmt
  :
  tls_vec.TlsByteVecU16 → core.fmt.Formatter → RustM ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::TlsByteVecU24}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 754:28-754:33
    Visibility: public -/
axiom tls_vec.TlsByteVecU24.Insts.CoreFmtDebug.fmt
  :
  tls_vec.TlsByteVecU24 → core.fmt.Formatter → RustM ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::tls_vec::{impl core::fmt::Debug for tls_codec::tls_vec::TlsByteVecU32}::fmt]:
    Source: 'tls_codec/src/tls_vec.rs', lines 754:28-754:33
    Visibility: public -/
axiom tls_vec.TlsByteVecU32.Insts.CoreFmtDebug.fmt
  :
  tls_vec.TlsByteVecU32 → core.fmt.Formatter → RustM ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [tls_codec::varint::{impl core::fmt::Debug for tls_codec::varint::TlsVarInt}::fmt]:
    Source: 'tls_codec/src/varint.rs', lines 6:9-6:14
    Visibility: public -/
axiom varint.TlsVarInt.Insts.CoreFmtDebug.fmt
  :
  varint.TlsVarInt → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

