-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [tls_codec]: proof obligations
import Aeneas
import CoreModels
import TlsCodec.Extraction.Types
import TlsCodec.Extraction.Funs
import TlsCodec.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace tls_codec

theorem len_add.spec.proof (a : Std.Usize) (b : Std.Usize) : len_add.spec a b
  := by sorry

theorem checked_len_add.spec.proof (a : Std.Usize) (b : Std.Usize) :
  checked_len_add.spec a b
  := by sorry

theorem checked_capacity.spec.proof (len : Std.Usize) :
  checked_capacity.spec len
  := by sorry

theorem checked_alloc_len.spec.proof (a : Std.Usize) (b : Std.Usize) :
  checked_alloc_len.spec a b
  := by sorry

theorem quic_vec.tls_serialize_bytes_len.spec.proof (bytes : Slice Std.U8) :
  quic_vec.tls_serialize_bytes_len.spec bytes
  := by sorry

theorem spec.u8_encode_decode.spec.proof (value : Std.U8) :
  spec.u8_encode_decode.spec value
  := by sorry

theorem spec.u8_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.u8_decode_encode.spec bytes
  := by sorry

theorem spec.u16_encode_decode.spec.proof (value : Std.U16) :
  spec.u16_encode_decode.spec value
  := by sorry

theorem spec.u16_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.u16_decode_encode.spec bytes
  := by sorry

theorem spec.u32_encode_decode.spec.proof (value : Std.U32) :
  spec.u32_encode_decode.spec value
  := by sorry

theorem spec.u32_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.u32_decode_encode.spec bytes
  := by sorry

theorem spec.u64_encode_decode.spec.proof (value : Std.U64) :
  spec.u64_encode_decode.spec value
  := by sorry

theorem spec.u64_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.u64_decode_encode.spec bytes
  := by sorry

theorem spec.u24_encode_decode.spec.proof (value : U24) :
  spec.u24_encode_decode.spec value
  := by sorry

theorem spec.u24_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.u24_decode_encode.spec bytes
  := by sorry

theorem spec.array4_encode_decode.spec.proof (value : Array Std.U8 4#usize) :
  spec.array4_encode_decode.spec value
  := by sorry

theorem spec.array4_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.array4_decode_encode.spec bytes
  := by sorry

theorem spec.option_u16_encode_decode.spec.proof
  (value : core.option.Option Std.U16) :
  spec.option_u16_encode_decode.spec value
  := by sorry

theorem spec.option_u16_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.option_u16_decode_encode.spec bytes
  := by sorry

theorem spec.varint_encode_decode.spec.proof (value : varint.TlsVarInt) :
  spec.varint_encode_decode.spec value
  := by sorry

theorem spec.varint_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.varint_decode_encode.spec bytes
  := by sorry

theorem spec.vlbytes_encode_decode.spec.proof (value : quic_vec.VLBytes) :
  spec.vlbytes_encode_decode.spec value
  := by sorry

theorem spec.vlbytes_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.vlbytes_decode_encode.spec bytes
  := by sorry

theorem spec.byte_vec_u8_encode_decode.spec.proof
  (value : tls_vec.TlsByteVecU8) : spec.byte_vec_u8_encode_decode.spec value
  := by sorry

theorem spec.byte_vec_u8_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.byte_vec_u8_decode_encode.spec bytes
  := by sorry

theorem spec.byte_vec_u16_encode_decode.spec.proof
  (value : tls_vec.TlsByteVecU16) : spec.byte_vec_u16_encode_decode.spec value
  := by sorry

theorem spec.byte_vec_u16_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.byte_vec_u16_decode_encode.spec bytes
  := by sorry

theorem spec.byte_vec_u24_encode_decode.spec.proof
  (value : tls_vec.TlsByteVecU24) : spec.byte_vec_u24_encode_decode.spec value
  := by sorry

theorem spec.byte_vec_u24_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.byte_vec_u24_decode_encode.spec bytes
  := by sorry

theorem spec.byte_vec_u32_encode_decode.spec.proof
  (value : tls_vec.TlsByteVecU32) : spec.byte_vec_u32_encode_decode.spec value
  := by sorry

theorem spec.byte_vec_u32_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.byte_vec_u32_decode_encode.spec bytes
  := by sorry

theorem spec.vec_u16_encode_decode.spec.proof (value : alloc.vec.Vec Std.U16) :
  spec.vec_u16_encode_decode.spec value
  := by sorry

theorem spec.vec_u16_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.vec_u16_decode_encode.spec bytes
  := by sorry

theorem spec.string_encode_decode.spec.proof (value : alloc.string.String) :
  spec.string_encode_decode.spec value
  := by sorry

theorem spec.string_decode_encode.spec.proof (bytes : Slice Std.U8) :
  spec.string_decode_encode.spec bytes
  := by sorry

theorem varint.check_min_len.spec.proof (_value : Std.U64) (_len : Std.Usize) :
  varint.check_min_len.spec _value _len
  := by sorry

theorem varint.calculate_value.spec.proof (byte : Std.U8) :
  varint.calculate_value.spec byte
  := by sorry

theorem
  DeserializeBytes.tls_deserialize_exact_bytes.default.spec.proof {Self : Type}
                                                                 (DeserializeBytesInst
                                                                 :
                                                                 DeserializeBytes
                                                                 Self)
  (bytes : Slice Std.U8) :
  DeserializeBytes.tls_deserialize_exact_bytes.default.spec
  DeserializeBytesInst bytes
  := by sorry

theorem U24.from_be_bytes.spec.proof (bytes : Array Std.U8 3#usize) :
  U24.from_be_bytes.spec bytes
  := by sorry

theorem U24.to_be_bytes.spec.proof (self : U24) : U24.to_be_bytes.spec self
  := by sorry

theorem Usize.Insts.CoreConvertFromU24.from.spec.proof (value : U24) :
  Usize.Insts.CoreConvertFromU24.from.spec value
  := by sorry

theorem U24.Insts.CoreConvertTryFromUsizeError.try_from.spec.proof
  (value : Std.Usize) :
  U24.Insts.CoreConvertTryFromUsizeError.try_from.spec value
  := by sorry

theorem
  ArrayU8LEN.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (LEN : Std.Usize) (bytes : Slice Std.U8) :
  ArrayU8LEN.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec LEN
  bytes
  := by sorry

theorem
  ArrayU8LEN.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   {LEN : Std.Usize} (self : Array Std.U8 LEN) :
  ArrayU8LEN.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem
  ArrayU8LEN.Insts.Tls_codecSize.tls_serialized_len.spec.proof {LEN :
                                                              Std.Usize}
  (self : Array Std.U8 LEN) :
  ArrayU8LEN.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  core.option.Option.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : core.option.Option T) :
  core.option.Option.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  Shared0Option.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type}
                                                                 (SizeInst :
                                                                 Size T)
  (self : core.option.Option T) :
  Shared0Option.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  core.option.Option.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   {T : Type} (SerializeBytesInst : SerializeBytes T)
  (self : core.option.Option T) :
  core.option.Option.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  SerializeBytesInst self
  := by sorry

theorem
  Shared0Option.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   {T : Type} (SerializeBytesInst : SerializeBytes T)
  (self : core.option.Option T) :
  Shared0Option.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  SerializeBytesInst self
  := by sorry

theorem
  core.option.Option.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} (DeserializeBytesInst : DeserializeBytes T)
  (bytes : Slice Std.U8) :
  core.option.Option.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  DeserializeBytesInst bytes
  := by sorry

theorem U8.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  U8.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec bytes
  := by sorry

theorem Shared0U8.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : Std.U8) :
  Shared0U8.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem U8.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : Std.U8) :
  U8.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem U8.Insts.Tls_codecSize.tls_serialized_len.spec.proof (self : Std.U8) :
  U8.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Shared0U8.Insts.Tls_codecSize.tls_serialized_len.spec.proof
  (self : Std.U8) : Shared0U8.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem U16.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  U16.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec bytes
  := by sorry

theorem Shared0U16.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : Std.U16) :
  Shared0U16.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem U16.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : Std.U16) :
  U16.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem U16.Insts.Tls_codecSize.tls_serialized_len.spec.proof (self : Std.U16)
  : U16.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Shared0U16.Insts.Tls_codecSize.tls_serialized_len.spec.proof
  (self : Std.U16) :
  Shared0U16.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem U24.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  U24.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec bytes
  := by sorry

theorem Shared0U24.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : U24) :
  Shared0U24.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem U24.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : U24) :
  U24.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem U24.Insts.Tls_codecSize.tls_serialized_len.spec.proof (self : U24) :
  U24.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Shared0U24.Insts.Tls_codecSize.tls_serialized_len.spec.proof
  (self : U24) : Shared0U24.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem U32.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  U32.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec bytes
  := by sorry

theorem Shared0U32.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : Std.U32) :
  Shared0U32.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem U32.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : Std.U32) :
  U32.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem U32.Insts.Tls_codecSize.tls_serialized_len.spec.proof (self : Std.U32)
  : U32.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Shared0U32.Insts.Tls_codecSize.tls_serialized_len.spec.proof
  (self : Std.U32) :
  Shared0U32.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem U64.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  U64.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec bytes
  := by sorry

theorem Shared0U64.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : Std.U64) :
  Shared0U64.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem U64.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : Std.U64) :
  U64.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem U64.Insts.Tls_codecSize.tls_serialized_len.spec.proof (self : Std.U64)
  : U64.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Shared0U64.Insts.Tls_codecSize.tls_serialized_len.spec.proof
  (self : Std.U64) :
  Shared0U64.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  Pair.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} {U : Type} (DeserializeBytesInst : DeserializeBytes T)
  (DeserializeBytesInst1 : DeserializeBytes U) (bytes : Slice Std.U8) :
  Pair.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  DeserializeBytesInst DeserializeBytesInst1 bytes
  := by sorry

theorem
  Pair.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type} {U : Type}
                                                        (SizeInst : Size T)
                                                        (SizeInst1 : Size U)
  (self : (T × U)) :
  Pair.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst SizeInst1 self
  := by sorry

theorem
  TupleTUV.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} {U : Type} {V : Type} (DeserializeBytesInst : DeserializeBytes T)
  (DeserializeBytesInst1 : DeserializeBytes U) (DeserializeBytesInst2 :
  DeserializeBytes V) (bytes : Slice Std.U8) :
  TupleTUV.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  DeserializeBytesInst DeserializeBytesInst1 DeserializeBytesInst2 bytes
  := by sorry

theorem
  TupleTUV.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type} {U :
                                                            Type} {V : Type}
                                                            (SizeInst : Size T)
                                                            (SizeInst1 : Size
                                                            U) (SizeInst2 :
                                                            Size V)
  (self : (T × U × V)) :
  TupleTUV.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst SizeInst1
  SizeInst2 self
  := by sorry

theorem Tuple.Insts.Tls_codecSize.tls_serialized_len.spec.proof (_ : Unit) :
  Tuple.Insts.Tls_codecSize.tls_serialized_len.spec ()
  := by sorry

theorem Tuple.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  Tuple.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec bytes
  := by sorry

theorem
  core.marker.PhantomData.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (self : core.marker.PhantomData T) :
  core.marker.PhantomData.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  core.marker.PhantomData.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (T : Type) (bytes : Slice Std.U8) :
  core.marker.PhantomData.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  T bytes
  := by sorry

theorem
  core.marker.PhantomData.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   {T : Type} (self : core.marker.PhantomData T) :
  core.marker.PhantomData.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  self
  := by sorry

theorem
  Box.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type} (SizeInst :
                                                       Size T) (self : T) :
  Box.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  Box.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof {T : Type}
                                                                  (SerializeBytesInst
                                                                  :
                                                                  SerializeBytes
                                                                  T) 
  (self : T) :
  Box.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec SerializeBytesInst
  self
  := by sorry

theorem quic_vec.ContentLength.new.spec.proof (value : varint.TlsVarInt) :
  quic_vec.ContentLength.new.spec value
  := by sorry

theorem quic_vec.ContentLength.from_usize.spec.proof (value : Std.Usize) :
  quic_vec.ContentLength.from_usize.spec value
  := by sorry

theorem
  quic_vec.ContentLength.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : quic_vec.ContentLength) :
  quic_vec.ContentLength.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  quic_vec.ContentLength.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  quic_vec.ContentLength.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  bytes
  := by sorry

theorem
  alloc.vec.Vec.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type}
                                                                 (SizeInst :
                                                                 Size T)
  (self : alloc.vec.Vec T) :
  alloc.vec.Vec.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  Shared0Vec.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type}
                                                              (SizeInst : Size
                                                              T)
  (self : alloc.vec.Vec T) :
  Shared0Vec.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  alloc.vec.Vec.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} (DeserializeBytesInst : DeserializeBytes T)
  (bytes : Slice Std.U8) :
  alloc.vec.Vec.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  DeserializeBytesInst bytes
  := by sorry

theorem
  quic_vec.VLBytes.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : quic_vec.VLBytes) :
  quic_vec.VLBytes.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem
  Shared0VLBytes.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : quic_vec.VLBytes) :
  Shared0VLBytes.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem
  Shared0Vec.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   {T : Type} (SerializeBytesInst : SerializeBytes T) (self : alloc.vec.Vec T)
  :
  Shared0Vec.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  SerializeBytesInst self
  := by sorry

theorem
  alloc.vec.Vec.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   {T : Type} (SerializeBytesInst : SerializeBytes T) (self : alloc.vec.Vec T)
  :
  alloc.vec.Vec.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  SerializeBytesInst self
  := by sorry

theorem
  Shared0Slice.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type}
                                                                (SizeInst :
                                                                Size T)
  (self : Slice T) :
  Shared0Slice.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem quic_vec.VLBytes.as_slice.spec.proof (self : quic_vec.VLBytes) :
  quic_vec.VLBytes.as_slice.spec self
  := by sorry

theorem quic_vec.VLBytes.push.spec.proof (self : quic_vec.VLBytes)
  (value : Std.U8) : quic_vec.VLBytes.push.spec self value
  := by sorry

theorem quic_vec.VLBytes.pop.spec.proof (self : quic_vec.VLBytes) :
  quic_vec.VLBytes.pop.spec self
  := by sorry

theorem quic_vec.VLBytes.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : quic_vec.VLBytes) :
  quic_vec.VLBytes.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  quic_vec.VLBytes.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  quic_vec.VLBytes.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  bytes
  := by sorry

theorem Shared0VLBytes.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : quic_vec.VLBytes) :
  Shared0VLBytes.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem quic_vec.VLByteVec.as_slice.spec.proof (self : quic_vec.VLByteVec) :
  quic_vec.VLByteVec.as_slice.spec self
  := by sorry

theorem quic_vec.VLByteVec.push.spec.proof (self : quic_vec.VLByteVec)
  (value : Std.U8) : quic_vec.VLByteVec.push.spec self value
  := by sorry

theorem quic_vec.VLByteVec.pop.spec.proof (self : quic_vec.VLByteVec) :
  quic_vec.VLByteVec.pop.spec self
  := by sorry

theorem quic_vec.VLByteVec.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : quic_vec.VLByteVec) :
  quic_vec.VLByteVec.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  quic_vec.VLByteVec.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  quic_vec.VLByteVec.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  bytes
  := by sorry

theorem Shared0VLByteVec.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : quic_vec.VLByteVec) :
  Shared0VLByteVec.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem quic_vec.VLByteSlice.as_slice.spec.proof (self : quic_vec.VLByteSlice)
  : quic_vec.VLByteSlice.as_slice.spec self
  := by sorry

theorem Shared0VLByteSlice.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : quic_vec.VLByteSlice) :
  Shared0VLByteSlice.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem quic_vec.VLByteSlice.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : quic_vec.VLByteSlice) :
  quic_vec.VLByteSlice.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  quic_vec.ContentLength.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : quic_vec.ContentLength) :
  quic_vec.ContentLength.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  self
  := by sorry

theorem
  quic_vec.VLByteSlice.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : quic_vec.VLByteSlice) :
  quic_vec.VLByteSlice.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  self
  := by sorry

theorem
  varint.TlsVarInt.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : varint.TlsVarInt) :
  varint.TlsVarInt.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem
  varint.TlsVarInt.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  varint.TlsVarInt.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  bytes
  := by sorry

theorem
  tls_vec.TlsByteVecU8.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : tls_vec.TlsByteVecU8) :
  tls_vec.TlsByteVecU8.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  self
  := by sorry

theorem
  tls_vec.TlsByteVecU8.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  tls_vec.TlsByteVecU8.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  bytes
  := by sorry

theorem
  tls_vec.TlsByteVecU16.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : tls_vec.TlsByteVecU16) :
  tls_vec.TlsByteVecU16.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  self
  := by sorry

theorem
  tls_vec.TlsByteVecU16.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  tls_vec.TlsByteVecU16.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  bytes
  := by sorry

theorem
  tls_vec.TlsByteVecU24.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : tls_vec.TlsByteVecU24) :
  tls_vec.TlsByteVecU24.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  self
  := by sorry

theorem
  tls_vec.TlsByteVecU24.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  tls_vec.TlsByteVecU24.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  bytes
  := by sorry

theorem
  tls_vec.TlsByteVecU32.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : tls_vec.TlsByteVecU32) :
  tls_vec.TlsByteVecU32.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  self
  := by sorry

theorem
  tls_vec.TlsByteVecU32.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  tls_vec.TlsByteVecU32.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  bytes
  := by sorry

theorem
  alloc.string.String.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : alloc.string.String) :
  alloc.string.String.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec
  self
  := by sorry

theorem
  alloc.string.String.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   (bytes : Slice Std.U8) :
  alloc.string.String.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  bytes
  := by sorry

theorem alloc.string.String.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : alloc.string.String) :
  alloc.string.String.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Str.Insts.Tls_codecSize.tls_serialized_len.spec.proof (self : Str) :
  Str.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Shared0Str.Insts.Tls_codecSize.tls_serialized_len.spec.proof
  (self : Str) : Shared0Str.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Str.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : Str) :
  Str.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem Shared0Str.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec.proof
   (self : Str) :
  Shared0Str.Insts.Tls_codecSerializeBytes.tls_serialize_bytes.spec self
  := by sorry

theorem tls_vec.TlsVecU8.new.spec.proof {T : Type} (vec : alloc.vec.Vec T) :
  tls_vec.TlsVecU8.new.spec vec
  := by sorry

theorem
  tls_vec.TlsVecU8.from_slice.spec.proof {T : Type} (corecloneCloneInst :
                                        core.clone.Clone T) (slice : Slice T) :
  tls_vec.TlsVecU8.from_slice.spec corecloneCloneInst slice
  := by sorry

theorem tls_vec.TlsVecU8.len.spec.proof {T : Type} (self : tls_vec.TlsVecU8 T)
  : tls_vec.TlsVecU8.len.spec self
  := by sorry

theorem tls_vec.TlsVecU8.is_empty.spec.proof {T : Type}
  (self : tls_vec.TlsVecU8 T) : tls_vec.TlsVecU8.is_empty.spec self
  := by sorry

theorem tls_vec.TlsVecU8.into_vec.spec.proof {T : Type}
  (self : tls_vec.TlsVecU8 T) : tls_vec.TlsVecU8.into_vec.spec self
  := by sorry

theorem tls_vec.TlsVecU8.push.spec.proof {T : Type} (self : tls_vec.TlsVecU8 T)
  (value : T) : tls_vec.TlsVecU8.push.spec self value
  := by sorry

theorem tls_vec.TlsVecU8.pop.spec.proof {T : Type} (self : tls_vec.TlsVecU8 T)
  : tls_vec.TlsVecU8.pop.spec self
  := by sorry

theorem tls_vec.TlsVecU8.remove.spec.proof {T : Type}
  (self : tls_vec.TlsVecU8 T) (index : Std.Usize) :
  tls_vec.TlsVecU8.remove.spec self index
  := by sorry

theorem tls_vec.TlsVecU8.get.spec.proof {T : Type} (self : tls_vec.TlsVecU8 T)
  (index : Std.Usize) : tls_vec.TlsVecU8.get.spec self index
  := by sorry

theorem tls_vec.TlsVecU8.len_len.spec.proof (T : Type) :
  tls_vec.TlsVecU8.len_len.spec T
  := by sorry

theorem
  tls_vec.TlsVecU8.Insts.CoreOpsIndexIndexUsizeT.index.spec.proof {T : Type}
  (self : tls_vec.TlsVecU8 T) (i : Std.Usize) :
  tls_vec.TlsVecU8.Insts.CoreOpsIndexIndexUsizeT.index.spec self i
  := by sorry

theorem
  tls_vec.TlsVecU8.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec.proof
   {T : Type} (self : tls_vec.TlsVecU8 T) (i : Std.Usize) :
  tls_vec.TlsVecU8.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec self i
  := by sorry

theorem
  tls_vec.TlsVecU8.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type}
                                                                    (SizeInst :
                                                                    Size T)
  (self : tls_vec.TlsVecU8 T) :
  tls_vec.TlsVecU8.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  Shared0TlsVecU8.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type}
                                                                   (SizeInst :
                                                                   Size T)
  (self : tls_vec.TlsVecU8 T) :
  Shared0TlsVecU8.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsVecU8.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} (DeserializeBytesInst : DeserializeBytes T)
  (bytes : Slice Std.U8) :
  tls_vec.TlsVecU8.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  DeserializeBytesInst bytes
  := by sorry

theorem
  tls_vec.TlsVecU8.tls_serialized_length.spec.proof {T : Type} (SizeInst : Size
                                                   T)
  (self : tls_vec.TlsVecU8 T) :
  tls_vec.TlsVecU8.tls_serialized_length.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsVecU8.deserialize_bytes.spec.proof {T : Type}
                                               (DeserializeBytesInst :
                                               DeserializeBytes T)
  (bytes : Slice Std.U8) :
  tls_vec.TlsVecU8.deserialize_bytes.spec DeserializeBytesInst bytes
  := by sorry

theorem tls_vec.TlsVecU16.new.spec.proof {T : Type} (vec : alloc.vec.Vec T) :
  tls_vec.TlsVecU16.new.spec vec
  := by sorry

theorem
  tls_vec.TlsVecU16.from_slice.spec.proof {T : Type} (corecloneCloneInst :
                                         core.clone.Clone T) (slice : Slice T)
  : tls_vec.TlsVecU16.from_slice.spec corecloneCloneInst slice
  := by sorry

theorem tls_vec.TlsVecU16.len.spec.proof {T : Type}
  (self : tls_vec.TlsVecU16 T) : tls_vec.TlsVecU16.len.spec self
  := by sorry

theorem tls_vec.TlsVecU16.is_empty.spec.proof {T : Type}
  (self : tls_vec.TlsVecU16 T) : tls_vec.TlsVecU16.is_empty.spec self
  := by sorry

theorem tls_vec.TlsVecU16.into_vec.spec.proof {T : Type}
  (self : tls_vec.TlsVecU16 T) : tls_vec.TlsVecU16.into_vec.spec self
  := by sorry

theorem tls_vec.TlsVecU16.push.spec.proof {T : Type}
  (self : tls_vec.TlsVecU16 T) (value : T) :
  tls_vec.TlsVecU16.push.spec self value
  := by sorry

theorem tls_vec.TlsVecU16.pop.spec.proof {T : Type}
  (self : tls_vec.TlsVecU16 T) : tls_vec.TlsVecU16.pop.spec self
  := by sorry

theorem tls_vec.TlsVecU16.remove.spec.proof {T : Type}
  (self : tls_vec.TlsVecU16 T) (index : Std.Usize) :
  tls_vec.TlsVecU16.remove.spec self index
  := by sorry

theorem tls_vec.TlsVecU16.get.spec.proof {T : Type}
  (self : tls_vec.TlsVecU16 T) (index : Std.Usize) :
  tls_vec.TlsVecU16.get.spec self index
  := by sorry

theorem tls_vec.TlsVecU16.len_len.spec.proof (T : Type) :
  tls_vec.TlsVecU16.len_len.spec T
  := by sorry

theorem
  tls_vec.TlsVecU16.Insts.CoreOpsIndexIndexUsizeT.index.spec.proof {T : Type}
  (self : tls_vec.TlsVecU16 T) (i : Std.Usize) :
  tls_vec.TlsVecU16.Insts.CoreOpsIndexIndexUsizeT.index.spec self i
  := by sorry

theorem
  tls_vec.TlsVecU16.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec.proof
   {T : Type} (self : tls_vec.TlsVecU16 T) (i : Std.Usize) :
  tls_vec.TlsVecU16.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec self i
  := by sorry

theorem
  tls_vec.TlsVecU16.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : tls_vec.TlsVecU16 T) :
  tls_vec.TlsVecU16.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  Shared0TlsVecU16.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type}
                                                                    (SizeInst :
                                                                    Size T)
  (self : tls_vec.TlsVecU16 T) :
  Shared0TlsVecU16.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsVecU16.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} (DeserializeBytesInst : DeserializeBytes T)
  (bytes : Slice Std.U8) :
  tls_vec.TlsVecU16.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  DeserializeBytesInst bytes
  := by sorry

theorem
  tls_vec.TlsVecU16.tls_serialized_length.spec.proof {T : Type} (SizeInst :
                                                    Size T)
  (self : tls_vec.TlsVecU16 T) :
  tls_vec.TlsVecU16.tls_serialized_length.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsVecU16.deserialize_bytes.spec.proof {T : Type}
                                                (DeserializeBytesInst :
                                                DeserializeBytes T)
  (bytes : Slice Std.U8) :
  tls_vec.TlsVecU16.deserialize_bytes.spec DeserializeBytesInst bytes
  := by sorry

theorem tls_vec.TlsVecU24.new.spec.proof {T : Type} (vec : alloc.vec.Vec T) :
  tls_vec.TlsVecU24.new.spec vec
  := by sorry

theorem
  tls_vec.TlsVecU24.from_slice.spec.proof {T : Type} (corecloneCloneInst :
                                         core.clone.Clone T) (slice : Slice T)
  : tls_vec.TlsVecU24.from_slice.spec corecloneCloneInst slice
  := by sorry

theorem tls_vec.TlsVecU24.len.spec.proof {T : Type}
  (self : tls_vec.TlsVecU24 T) : tls_vec.TlsVecU24.len.spec self
  := by sorry

theorem tls_vec.TlsVecU24.is_empty.spec.proof {T : Type}
  (self : tls_vec.TlsVecU24 T) : tls_vec.TlsVecU24.is_empty.spec self
  := by sorry

theorem tls_vec.TlsVecU24.into_vec.spec.proof {T : Type}
  (self : tls_vec.TlsVecU24 T) : tls_vec.TlsVecU24.into_vec.spec self
  := by sorry

theorem tls_vec.TlsVecU24.push.spec.proof {T : Type}
  (self : tls_vec.TlsVecU24 T) (value : T) :
  tls_vec.TlsVecU24.push.spec self value
  := by sorry

theorem tls_vec.TlsVecU24.pop.spec.proof {T : Type}
  (self : tls_vec.TlsVecU24 T) : tls_vec.TlsVecU24.pop.spec self
  := by sorry

theorem tls_vec.TlsVecU24.remove.spec.proof {T : Type}
  (self : tls_vec.TlsVecU24 T) (index : Std.Usize) :
  tls_vec.TlsVecU24.remove.spec self index
  := by sorry

theorem tls_vec.TlsVecU24.get.spec.proof {T : Type}
  (self : tls_vec.TlsVecU24 T) (index : Std.Usize) :
  tls_vec.TlsVecU24.get.spec self index
  := by sorry

theorem tls_vec.TlsVecU24.len_len.spec.proof (T : Type) :
  tls_vec.TlsVecU24.len_len.spec T
  := by sorry

theorem
  tls_vec.TlsVecU24.Insts.CoreOpsIndexIndexUsizeT.index.spec.proof {T : Type}
  (self : tls_vec.TlsVecU24 T) (i : Std.Usize) :
  tls_vec.TlsVecU24.Insts.CoreOpsIndexIndexUsizeT.index.spec self i
  := by sorry

theorem
  tls_vec.TlsVecU24.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec.proof
   {T : Type} (self : tls_vec.TlsVecU24 T) (i : Std.Usize) :
  tls_vec.TlsVecU24.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec self i
  := by sorry

theorem
  tls_vec.TlsVecU24.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : tls_vec.TlsVecU24 T) :
  tls_vec.TlsVecU24.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  Shared0TlsVecU24.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type}
                                                                    (SizeInst :
                                                                    Size T)
  (self : tls_vec.TlsVecU24 T) :
  Shared0TlsVecU24.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsVecU24.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} (DeserializeBytesInst : DeserializeBytes T)
  (bytes : Slice Std.U8) :
  tls_vec.TlsVecU24.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  DeserializeBytesInst bytes
  := by sorry

theorem
  tls_vec.TlsVecU24.tls_serialized_length.spec.proof {T : Type} (SizeInst :
                                                    Size T)
  (self : tls_vec.TlsVecU24 T) :
  tls_vec.TlsVecU24.tls_serialized_length.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsVecU24.deserialize_bytes.spec.proof {T : Type}
                                                (DeserializeBytesInst :
                                                DeserializeBytes T)
  (bytes : Slice Std.U8) :
  tls_vec.TlsVecU24.deserialize_bytes.spec DeserializeBytesInst bytes
  := by sorry

theorem tls_vec.TlsVecU32.new.spec.proof {T : Type} (vec : alloc.vec.Vec T) :
  tls_vec.TlsVecU32.new.spec vec
  := by sorry

theorem
  tls_vec.TlsVecU32.from_slice.spec.proof {T : Type} (corecloneCloneInst :
                                         core.clone.Clone T) (slice : Slice T)
  : tls_vec.TlsVecU32.from_slice.spec corecloneCloneInst slice
  := by sorry

theorem tls_vec.TlsVecU32.len.spec.proof {T : Type}
  (self : tls_vec.TlsVecU32 T) : tls_vec.TlsVecU32.len.spec self
  := by sorry

theorem tls_vec.TlsVecU32.is_empty.spec.proof {T : Type}
  (self : tls_vec.TlsVecU32 T) : tls_vec.TlsVecU32.is_empty.spec self
  := by sorry

theorem tls_vec.TlsVecU32.into_vec.spec.proof {T : Type}
  (self : tls_vec.TlsVecU32 T) : tls_vec.TlsVecU32.into_vec.spec self
  := by sorry

theorem tls_vec.TlsVecU32.push.spec.proof {T : Type}
  (self : tls_vec.TlsVecU32 T) (value : T) :
  tls_vec.TlsVecU32.push.spec self value
  := by sorry

theorem tls_vec.TlsVecU32.pop.spec.proof {T : Type}
  (self : tls_vec.TlsVecU32 T) : tls_vec.TlsVecU32.pop.spec self
  := by sorry

theorem tls_vec.TlsVecU32.remove.spec.proof {T : Type}
  (self : tls_vec.TlsVecU32 T) (index : Std.Usize) :
  tls_vec.TlsVecU32.remove.spec self index
  := by sorry

theorem tls_vec.TlsVecU32.get.spec.proof {T : Type}
  (self : tls_vec.TlsVecU32 T) (index : Std.Usize) :
  tls_vec.TlsVecU32.get.spec self index
  := by sorry

theorem tls_vec.TlsVecU32.len_len.spec.proof (T : Type) :
  tls_vec.TlsVecU32.len_len.spec T
  := by sorry

theorem
  tls_vec.TlsVecU32.Insts.CoreOpsIndexIndexUsizeT.index.spec.proof {T : Type}
  (self : tls_vec.TlsVecU32 T) (i : Std.Usize) :
  tls_vec.TlsVecU32.Insts.CoreOpsIndexIndexUsizeT.index.spec self i
  := by sorry

theorem
  tls_vec.TlsVecU32.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec.proof
   {T : Type} (self : tls_vec.TlsVecU32 T) (i : Std.Usize) :
  tls_vec.TlsVecU32.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec self i
  := by sorry

theorem
  tls_vec.TlsVecU32.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : tls_vec.TlsVecU32 T) :
  tls_vec.TlsVecU32.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  Shared0TlsVecU32.Insts.Tls_codecSize.tls_serialized_len.spec.proof {T : Type}
                                                                    (SizeInst :
                                                                    Size T)
  (self : tls_vec.TlsVecU32 T) :
  Shared0TlsVecU32.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsVecU32.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} (DeserializeBytesInst : DeserializeBytes T)
  (bytes : Slice Std.U8) :
  tls_vec.TlsVecU32.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  DeserializeBytesInst bytes
  := by sorry

theorem
  tls_vec.TlsVecU32.tls_serialized_length.spec.proof {T : Type} (SizeInst :
                                                    Size T)
  (self : tls_vec.TlsVecU32 T) :
  tls_vec.TlsVecU32.tls_serialized_length.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsVecU32.deserialize_bytes.spec.proof {T : Type}
                                                (DeserializeBytesInst :
                                                DeserializeBytes T)
  (bytes : Slice Std.U8) :
  tls_vec.TlsVecU32.deserialize_bytes.spec DeserializeBytesInst bytes
  := by sorry

theorem tls_vec.TlsByteVecU8.new.spec.proof (vec : alloc.vec.Vec Std.U8) :
  tls_vec.TlsByteVecU8.new.spec vec
  := by sorry

theorem
  tls_vec.TlsByteVecU8.from_slice.spec.proof (corecloneCloneU8Inst :
                                            core.clone.Clone Std.U8)
  (slice : Slice Std.U8) :
  tls_vec.TlsByteVecU8.from_slice.spec corecloneCloneU8Inst slice
  := by sorry

theorem tls_vec.TlsByteVecU8.len.spec.proof (self : tls_vec.TlsByteVecU8) :
  tls_vec.TlsByteVecU8.len.spec self
  := by sorry

theorem tls_vec.TlsByteVecU8.is_empty.spec.proof (self : tls_vec.TlsByteVecU8)
  : tls_vec.TlsByteVecU8.is_empty.spec self
  := by sorry

theorem tls_vec.TlsByteVecU8.into_vec.spec.proof (self : tls_vec.TlsByteVecU8)
  : tls_vec.TlsByteVecU8.into_vec.spec self
  := by sorry

theorem tls_vec.TlsByteVecU8.push.spec.proof (self : tls_vec.TlsByteVecU8)
  (value : Std.U8) : tls_vec.TlsByteVecU8.push.spec self value
  := by sorry

theorem tls_vec.TlsByteVecU8.pop.spec.proof (self : tls_vec.TlsByteVecU8) :
  tls_vec.TlsByteVecU8.pop.spec self
  := by sorry

theorem tls_vec.TlsByteVecU8.remove.spec.proof (self : tls_vec.TlsByteVecU8)
  (index : Std.Usize) : tls_vec.TlsByteVecU8.remove.spec self index
  := by sorry

theorem tls_vec.TlsByteVecU8.get.spec.proof (self : tls_vec.TlsByteVecU8)
  (index : Std.Usize) : tls_vec.TlsByteVecU8.get.spec self index
  := by sorry

theorem tls_vec.TlsByteVecU8.len_len.spec.proof :
  tls_vec.TlsByteVecU8.len_len.spec
  := by sorry

theorem tls_vec.TlsByteVecU8.Insts.CoreOpsIndexIndexUsizeU8.index.spec.proof
   (self : tls_vec.TlsByteVecU8) (i : Std.Usize) :
  tls_vec.TlsByteVecU8.Insts.CoreOpsIndexIndexUsizeU8.index.spec self i
  := by sorry

theorem
  tls_vec.TlsByteVecU8.Insts.CoreOpsIndexIndexMutUsizeU8.index_mut.spec.proof
   (self : tls_vec.TlsByteVecU8) (i : Std.Usize) :
  tls_vec.TlsByteVecU8.Insts.CoreOpsIndexIndexMutUsizeU8.index_mut.spec self i
  := by sorry

theorem tls_vec.TlsByteVecU8.assert_written_bytes.spec.proof
  (self : tls_vec.TlsByteVecU8) (tls_serialized_len : Std.Usize)
  (written : Std.Usize) :
  tls_vec.TlsByteVecU8.assert_written_bytes.spec self tls_serialized_len
  written
  := by sorry

theorem tls_vec.TlsByteVecU8.serialize_bytes_bytes.spec.proof
  (self : tls_vec.TlsByteVecU8) :
  tls_vec.TlsByteVecU8.serialize_bytes_bytes.spec self
  := by sorry

theorem tls_vec.TlsByteVecU8.tls_serialized_byte_length.spec.proof
  (self : tls_vec.TlsByteVecU8) :
  tls_vec.TlsByteVecU8.tls_serialized_byte_length.spec self
  := by sorry

theorem tls_vec.TlsByteVecU8.deserialize_bytes_bytes.spec.proof
  (bytes : Slice Std.U8) :
  tls_vec.TlsByteVecU8.deserialize_bytes_bytes.spec bytes
  := by sorry

theorem tls_vec.TlsByteVecU8.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteVecU8) :
  tls_vec.TlsByteVecU8.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Shared0TlsByteVecU8.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteVecU8) :
  Shared0TlsByteVecU8.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem tls_vec.TlsByteVecU16.new.spec.proof (vec : alloc.vec.Vec Std.U8) :
  tls_vec.TlsByteVecU16.new.spec vec
  := by sorry

theorem
  tls_vec.TlsByteVecU16.from_slice.spec.proof (corecloneCloneU8Inst :
                                             core.clone.Clone Std.U8)
  (slice : Slice Std.U8) :
  tls_vec.TlsByteVecU16.from_slice.spec corecloneCloneU8Inst slice
  := by sorry

theorem tls_vec.TlsByteVecU16.len.spec.proof (self : tls_vec.TlsByteVecU16) :
  tls_vec.TlsByteVecU16.len.spec self
  := by sorry

theorem tls_vec.TlsByteVecU16.is_empty.spec.proof
  (self : tls_vec.TlsByteVecU16) : tls_vec.TlsByteVecU16.is_empty.spec self
  := by sorry

theorem tls_vec.TlsByteVecU16.into_vec.spec.proof
  (self : tls_vec.TlsByteVecU16) : tls_vec.TlsByteVecU16.into_vec.spec self
  := by sorry

theorem tls_vec.TlsByteVecU16.push.spec.proof (self : tls_vec.TlsByteVecU16)
  (value : Std.U8) : tls_vec.TlsByteVecU16.push.spec self value
  := by sorry

theorem tls_vec.TlsByteVecU16.pop.spec.proof (self : tls_vec.TlsByteVecU16) :
  tls_vec.TlsByteVecU16.pop.spec self
  := by sorry

theorem tls_vec.TlsByteVecU16.remove.spec.proof (self : tls_vec.TlsByteVecU16)
  (index : Std.Usize) : tls_vec.TlsByteVecU16.remove.spec self index
  := by sorry

theorem tls_vec.TlsByteVecU16.get.spec.proof (self : tls_vec.TlsByteVecU16)
  (index : Std.Usize) : tls_vec.TlsByteVecU16.get.spec self index
  := by sorry

theorem tls_vec.TlsByteVecU16.len_len.spec.proof :
  tls_vec.TlsByteVecU16.len_len.spec
  := by sorry

theorem tls_vec.TlsByteVecU16.Insts.CoreOpsIndexIndexUsizeU8.index.spec.proof
   (self : tls_vec.TlsByteVecU16) (i : Std.Usize) :
  tls_vec.TlsByteVecU16.Insts.CoreOpsIndexIndexUsizeU8.index.spec self i
  := by sorry

theorem
  tls_vec.TlsByteVecU16.Insts.CoreOpsIndexIndexMutUsizeU8.index_mut.spec.proof
   (self : tls_vec.TlsByteVecU16) (i : Std.Usize) :
  tls_vec.TlsByteVecU16.Insts.CoreOpsIndexIndexMutUsizeU8.index_mut.spec self i
  := by sorry

theorem tls_vec.TlsByteVecU16.assert_written_bytes.spec.proof
  (self : tls_vec.TlsByteVecU16) (tls_serialized_len : Std.Usize)
  (written : Std.Usize) :
  tls_vec.TlsByteVecU16.assert_written_bytes.spec self tls_serialized_len
  written
  := by sorry

theorem tls_vec.TlsByteVecU16.serialize_bytes_bytes.spec.proof
  (self : tls_vec.TlsByteVecU16) :
  tls_vec.TlsByteVecU16.serialize_bytes_bytes.spec self
  := by sorry

theorem tls_vec.TlsByteVecU16.tls_serialized_byte_length.spec.proof
  (self : tls_vec.TlsByteVecU16) :
  tls_vec.TlsByteVecU16.tls_serialized_byte_length.spec self
  := by sorry

theorem tls_vec.TlsByteVecU16.deserialize_bytes_bytes.spec.proof
  (bytes : Slice Std.U8) :
  tls_vec.TlsByteVecU16.deserialize_bytes_bytes.spec bytes
  := by sorry

theorem tls_vec.TlsByteVecU16.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteVecU16) :
  tls_vec.TlsByteVecU16.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Shared0TlsByteVecU16.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteVecU16) :
  Shared0TlsByteVecU16.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem tls_vec.TlsByteVecU24.new.spec.proof (vec : alloc.vec.Vec Std.U8) :
  tls_vec.TlsByteVecU24.new.spec vec
  := by sorry

theorem
  tls_vec.TlsByteVecU24.from_slice.spec.proof (corecloneCloneU8Inst :
                                             core.clone.Clone Std.U8)
  (slice : Slice Std.U8) :
  tls_vec.TlsByteVecU24.from_slice.spec corecloneCloneU8Inst slice
  := by sorry

theorem tls_vec.TlsByteVecU24.len.spec.proof (self : tls_vec.TlsByteVecU24) :
  tls_vec.TlsByteVecU24.len.spec self
  := by sorry

theorem tls_vec.TlsByteVecU24.is_empty.spec.proof
  (self : tls_vec.TlsByteVecU24) : tls_vec.TlsByteVecU24.is_empty.spec self
  := by sorry

theorem tls_vec.TlsByteVecU24.into_vec.spec.proof
  (self : tls_vec.TlsByteVecU24) : tls_vec.TlsByteVecU24.into_vec.spec self
  := by sorry

theorem tls_vec.TlsByteVecU24.push.spec.proof (self : tls_vec.TlsByteVecU24)
  (value : Std.U8) : tls_vec.TlsByteVecU24.push.spec self value
  := by sorry

theorem tls_vec.TlsByteVecU24.pop.spec.proof (self : tls_vec.TlsByteVecU24) :
  tls_vec.TlsByteVecU24.pop.spec self
  := by sorry

theorem tls_vec.TlsByteVecU24.remove.spec.proof (self : tls_vec.TlsByteVecU24)
  (index : Std.Usize) : tls_vec.TlsByteVecU24.remove.spec self index
  := by sorry

theorem tls_vec.TlsByteVecU24.get.spec.proof (self : tls_vec.TlsByteVecU24)
  (index : Std.Usize) : tls_vec.TlsByteVecU24.get.spec self index
  := by sorry

theorem tls_vec.TlsByteVecU24.len_len.spec.proof :
  tls_vec.TlsByteVecU24.len_len.spec
  := by sorry

theorem tls_vec.TlsByteVecU24.Insts.CoreOpsIndexIndexUsizeU8.index.spec.proof
   (self : tls_vec.TlsByteVecU24) (i : Std.Usize) :
  tls_vec.TlsByteVecU24.Insts.CoreOpsIndexIndexUsizeU8.index.spec self i
  := by sorry

theorem
  tls_vec.TlsByteVecU24.Insts.CoreOpsIndexIndexMutUsizeU8.index_mut.spec.proof
   (self : tls_vec.TlsByteVecU24) (i : Std.Usize) :
  tls_vec.TlsByteVecU24.Insts.CoreOpsIndexIndexMutUsizeU8.index_mut.spec self i
  := by sorry

theorem tls_vec.TlsByteVecU24.assert_written_bytes.spec.proof
  (self : tls_vec.TlsByteVecU24) (tls_serialized_len : Std.Usize)
  (written : Std.Usize) :
  tls_vec.TlsByteVecU24.assert_written_bytes.spec self tls_serialized_len
  written
  := by sorry

theorem tls_vec.TlsByteVecU24.serialize_bytes_bytes.spec.proof
  (self : tls_vec.TlsByteVecU24) :
  tls_vec.TlsByteVecU24.serialize_bytes_bytes.spec self
  := by sorry

theorem tls_vec.TlsByteVecU24.tls_serialized_byte_length.spec.proof
  (self : tls_vec.TlsByteVecU24) :
  tls_vec.TlsByteVecU24.tls_serialized_byte_length.spec self
  := by sorry

theorem tls_vec.TlsByteVecU24.deserialize_bytes_bytes.spec.proof
  (bytes : Slice Std.U8) :
  tls_vec.TlsByteVecU24.deserialize_bytes_bytes.spec bytes
  := by sorry

theorem tls_vec.TlsByteVecU24.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteVecU24) :
  tls_vec.TlsByteVecU24.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Shared0TlsByteVecU24.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteVecU24) :
  Shared0TlsByteVecU24.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem tls_vec.TlsByteVecU32.new.spec.proof (vec : alloc.vec.Vec Std.U8) :
  tls_vec.TlsByteVecU32.new.spec vec
  := by sorry

theorem
  tls_vec.TlsByteVecU32.from_slice.spec.proof (corecloneCloneU8Inst :
                                             core.clone.Clone Std.U8)
  (slice : Slice Std.U8) :
  tls_vec.TlsByteVecU32.from_slice.spec corecloneCloneU8Inst slice
  := by sorry

theorem tls_vec.TlsByteVecU32.len.spec.proof (self : tls_vec.TlsByteVecU32) :
  tls_vec.TlsByteVecU32.len.spec self
  := by sorry

theorem tls_vec.TlsByteVecU32.is_empty.spec.proof
  (self : tls_vec.TlsByteVecU32) : tls_vec.TlsByteVecU32.is_empty.spec self
  := by sorry

theorem tls_vec.TlsByteVecU32.into_vec.spec.proof
  (self : tls_vec.TlsByteVecU32) : tls_vec.TlsByteVecU32.into_vec.spec self
  := by sorry

theorem tls_vec.TlsByteVecU32.push.spec.proof (self : tls_vec.TlsByteVecU32)
  (value : Std.U8) : tls_vec.TlsByteVecU32.push.spec self value
  := by sorry

theorem tls_vec.TlsByteVecU32.pop.spec.proof (self : tls_vec.TlsByteVecU32) :
  tls_vec.TlsByteVecU32.pop.spec self
  := by sorry

theorem tls_vec.TlsByteVecU32.remove.spec.proof (self : tls_vec.TlsByteVecU32)
  (index : Std.Usize) : tls_vec.TlsByteVecU32.remove.spec self index
  := by sorry

theorem tls_vec.TlsByteVecU32.get.spec.proof (self : tls_vec.TlsByteVecU32)
  (index : Std.Usize) : tls_vec.TlsByteVecU32.get.spec self index
  := by sorry

theorem tls_vec.TlsByteVecU32.len_len.spec.proof :
  tls_vec.TlsByteVecU32.len_len.spec
  := by sorry

theorem tls_vec.TlsByteVecU32.Insts.CoreOpsIndexIndexUsizeU8.index.spec.proof
   (self : tls_vec.TlsByteVecU32) (i : Std.Usize) :
  tls_vec.TlsByteVecU32.Insts.CoreOpsIndexIndexUsizeU8.index.spec self i
  := by sorry

theorem
  tls_vec.TlsByteVecU32.Insts.CoreOpsIndexIndexMutUsizeU8.index_mut.spec.proof
   (self : tls_vec.TlsByteVecU32) (i : Std.Usize) :
  tls_vec.TlsByteVecU32.Insts.CoreOpsIndexIndexMutUsizeU8.index_mut.spec self i
  := by sorry

theorem tls_vec.TlsByteVecU32.assert_written_bytes.spec.proof
  (self : tls_vec.TlsByteVecU32) (tls_serialized_len : Std.Usize)
  (written : Std.Usize) :
  tls_vec.TlsByteVecU32.assert_written_bytes.spec self tls_serialized_len
  written
  := by sorry

theorem tls_vec.TlsByteVecU32.serialize_bytes_bytes.spec.proof
  (self : tls_vec.TlsByteVecU32) :
  tls_vec.TlsByteVecU32.serialize_bytes_bytes.spec self
  := by sorry

theorem tls_vec.TlsByteVecU32.tls_serialized_byte_length.spec.proof
  (self : tls_vec.TlsByteVecU32) :
  tls_vec.TlsByteVecU32.tls_serialized_byte_length.spec self
  := by sorry

theorem tls_vec.TlsByteVecU32.deserialize_bytes_bytes.spec.proof
  (bytes : Slice Std.U8) :
  tls_vec.TlsByteVecU32.deserialize_bytes_bytes.spec bytes
  := by sorry

theorem tls_vec.TlsByteVecU32.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteVecU32) :
  tls_vec.TlsByteVecU32.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem Shared0TlsByteVecU32.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteVecU32) :
  Shared0TlsByteVecU32.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.new.spec.proof {T : Type} (zeroizeZeroizeInst :
                                       zeroize.Zeroize T)
  (vec : alloc.vec.Vec T) :
  tls_vec.SecretTlsVecU8.new.spec zeroizeZeroizeInst vec
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.from_slice.spec.proof {T : Type} (zeroizeZeroizeInst :
                                              zeroize.Zeroize T)
                                              (corecloneCloneInst :
                                              core.clone.Clone T)
  (slice : Slice T) :
  tls_vec.SecretTlsVecU8.from_slice.spec zeroizeZeroizeInst corecloneCloneInst
  slice
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.len.spec.proof {T : Type} (zeroizeZeroizeInst :
                                       zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU8 T) :
  tls_vec.SecretTlsVecU8.len.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.is_empty.spec.proof {T : Type} (zeroizeZeroizeInst :
                                            zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU8 T) :
  tls_vec.SecretTlsVecU8.is_empty.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.into_vec.spec.proof {T : Type} (zeroizeZeroizeInst :
                                            zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU8 T) :
  tls_vec.SecretTlsVecU8.into_vec.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.push.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU8 T) (value : T) :
  tls_vec.SecretTlsVecU8.push.spec zeroizeZeroizeInst self value
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.pop.spec.proof {T : Type} (zeroizeZeroizeInst :
                                       zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU8 T) :
  tls_vec.SecretTlsVecU8.pop.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.remove.spec.proof {T : Type} (zeroizeZeroizeInst :
                                          zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU8 T) (index : Std.Usize) :
  tls_vec.SecretTlsVecU8.remove.spec zeroizeZeroizeInst self index
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.get.spec.proof {T : Type} (zeroizeZeroizeInst :
                                       zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU8 T) (index : Std.Usize) :
  tls_vec.SecretTlsVecU8.get.spec zeroizeZeroizeInst self index
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.len_len.spec.proof {T : Type} (zeroizeZeroizeInst :
                                           zeroize.Zeroize T) :
  tls_vec.SecretTlsVecU8.len_len.spec zeroizeZeroizeInst
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.Insts.CoreOpsIndexIndexUsizeT.index.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU8 T) (i : Std.Usize) :
  tls_vec.SecretTlsVecU8.Insts.CoreOpsIndexIndexUsizeT.index.spec
  zeroizeZeroizeInst self i
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU8 T) (i : Std.Usize) :
  tls_vec.SecretTlsVecU8.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec
  zeroizeZeroizeInst self i
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (SizeInst : Size T)
  (self : tls_vec.SecretTlsVecU8 T) :
  tls_vec.SecretTlsVecU8.Insts.Tls_codecSize.tls_serialized_len.spec
  zeroizeZeroizeInst SizeInst self
  := by sorry

theorem
  Shared0SecretTlsVecU8.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (SizeInst : Size T)
  (self : tls_vec.SecretTlsVecU8 T) :
  Shared0SecretTlsVecU8.Insts.Tls_codecSize.tls_serialized_len.spec
  zeroizeZeroizeInst SizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (DeserializeBytesInst :
  DeserializeBytes T) (bytes : Slice Std.U8) :
  tls_vec.SecretTlsVecU8.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  zeroizeZeroizeInst DeserializeBytesInst bytes
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.tls_serialized_length.spec.proof {T : Type} (SizeInst
                                                         : Size T)
                                                         (zeroizeZeroizeInst :
                                                         zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU8 T) :
  tls_vec.SecretTlsVecU8.tls_serialized_length.spec SizeInst zeroizeZeroizeInst
  self
  := by sorry

theorem
  tls_vec.SecretTlsVecU8.deserialize_bytes.spec.proof {T : Type}
                                                     (DeserializeBytesInst :
                                                     DeserializeBytes T)
                                                     (zeroizeZeroizeInst :
                                                     zeroize.Zeroize T)
  (bytes : Slice Std.U8) :
  tls_vec.SecretTlsVecU8.deserialize_bytes.spec DeserializeBytesInst
  zeroizeZeroizeInst bytes
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.new.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (vec : alloc.vec.Vec T) :
  tls_vec.SecretTlsVecU16.new.spec zeroizeZeroizeInst vec
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.from_slice.spec.proof {T : Type} (zeroizeZeroizeInst
                                               : zeroize.Zeroize T)
                                               (corecloneCloneInst :
                                               core.clone.Clone T)
  (slice : Slice T) :
  tls_vec.SecretTlsVecU16.from_slice.spec zeroizeZeroizeInst corecloneCloneInst
  slice
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.len.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU16 T) :
  tls_vec.SecretTlsVecU16.len.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.is_empty.spec.proof {T : Type} (zeroizeZeroizeInst :
                                             zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU16 T) :
  tls_vec.SecretTlsVecU16.is_empty.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.into_vec.spec.proof {T : Type} (zeroizeZeroizeInst :
                                             zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU16 T) :
  tls_vec.SecretTlsVecU16.into_vec.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.push.spec.proof {T : Type} (zeroizeZeroizeInst :
                                         zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU16 T) (value : T) :
  tls_vec.SecretTlsVecU16.push.spec zeroizeZeroizeInst self value
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.pop.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU16 T) :
  tls_vec.SecretTlsVecU16.pop.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.remove.spec.proof {T : Type} (zeroizeZeroizeInst :
                                           zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU16 T) (index : Std.Usize) :
  tls_vec.SecretTlsVecU16.remove.spec zeroizeZeroizeInst self index
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.get.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU16 T) (index : Std.Usize) :
  tls_vec.SecretTlsVecU16.get.spec zeroizeZeroizeInst self index
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.len_len.spec.proof {T : Type} (zeroizeZeroizeInst :
                                            zeroize.Zeroize T) :
  tls_vec.SecretTlsVecU16.len_len.spec zeroizeZeroizeInst
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.Insts.CoreOpsIndexIndexUsizeT.index.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU16 T) (i : Std.Usize) :
  tls_vec.SecretTlsVecU16.Insts.CoreOpsIndexIndexUsizeT.index.spec
  zeroizeZeroizeInst self i
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU16 T) (i : Std.Usize) :
  tls_vec.SecretTlsVecU16.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec
  zeroizeZeroizeInst self i
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (SizeInst : Size T)
  (self : tls_vec.SecretTlsVecU16 T) :
  tls_vec.SecretTlsVecU16.Insts.Tls_codecSize.tls_serialized_len.spec
  zeroizeZeroizeInst SizeInst self
  := by sorry

theorem
  Shared0SecretTlsVecU16.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (SizeInst : Size T)
  (self : tls_vec.SecretTlsVecU16 T) :
  Shared0SecretTlsVecU16.Insts.Tls_codecSize.tls_serialized_len.spec
  zeroizeZeroizeInst SizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (DeserializeBytesInst :
  DeserializeBytes T) (bytes : Slice Std.U8) :
  tls_vec.SecretTlsVecU16.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  zeroizeZeroizeInst DeserializeBytesInst bytes
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.tls_serialized_length.spec.proof {T : Type} (SizeInst
                                                          : Size T)
                                                          (zeroizeZeroizeInst :
                                                          zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU16 T) :
  tls_vec.SecretTlsVecU16.tls_serialized_length.spec SizeInst
  zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU16.deserialize_bytes.spec.proof {T : Type}
                                                      (DeserializeBytesInst :
                                                      DeserializeBytes T)
                                                      (zeroizeZeroizeInst :
                                                      zeroize.Zeroize T)
  (bytes : Slice Std.U8) :
  tls_vec.SecretTlsVecU16.deserialize_bytes.spec DeserializeBytesInst
  zeroizeZeroizeInst bytes
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.new.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (vec : alloc.vec.Vec T) :
  tls_vec.SecretTlsVecU24.new.spec zeroizeZeroizeInst vec
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.from_slice.spec.proof {T : Type} (zeroizeZeroizeInst
                                               : zeroize.Zeroize T)
                                               (corecloneCloneInst :
                                               core.clone.Clone T)
  (slice : Slice T) :
  tls_vec.SecretTlsVecU24.from_slice.spec zeroizeZeroizeInst corecloneCloneInst
  slice
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.len.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU24 T) :
  tls_vec.SecretTlsVecU24.len.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.is_empty.spec.proof {T : Type} (zeroizeZeroizeInst :
                                             zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU24 T) :
  tls_vec.SecretTlsVecU24.is_empty.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.into_vec.spec.proof {T : Type} (zeroizeZeroizeInst :
                                             zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU24 T) :
  tls_vec.SecretTlsVecU24.into_vec.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.push.spec.proof {T : Type} (zeroizeZeroizeInst :
                                         zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU24 T) (value : T) :
  tls_vec.SecretTlsVecU24.push.spec zeroizeZeroizeInst self value
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.pop.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU24 T) :
  tls_vec.SecretTlsVecU24.pop.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.remove.spec.proof {T : Type} (zeroizeZeroizeInst :
                                           zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU24 T) (index : Std.Usize) :
  tls_vec.SecretTlsVecU24.remove.spec zeroizeZeroizeInst self index
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.get.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU24 T) (index : Std.Usize) :
  tls_vec.SecretTlsVecU24.get.spec zeroizeZeroizeInst self index
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.len_len.spec.proof {T : Type} (zeroizeZeroizeInst :
                                            zeroize.Zeroize T) :
  tls_vec.SecretTlsVecU24.len_len.spec zeroizeZeroizeInst
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.Insts.CoreOpsIndexIndexUsizeT.index.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU24 T) (i : Std.Usize) :
  tls_vec.SecretTlsVecU24.Insts.CoreOpsIndexIndexUsizeT.index.spec
  zeroizeZeroizeInst self i
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU24 T) (i : Std.Usize) :
  tls_vec.SecretTlsVecU24.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec
  zeroizeZeroizeInst self i
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (SizeInst : Size T)
  (self : tls_vec.SecretTlsVecU24 T) :
  tls_vec.SecretTlsVecU24.Insts.Tls_codecSize.tls_serialized_len.spec
  zeroizeZeroizeInst SizeInst self
  := by sorry

theorem
  Shared0SecretTlsVecU24.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (SizeInst : Size T)
  (self : tls_vec.SecretTlsVecU24 T) :
  Shared0SecretTlsVecU24.Insts.Tls_codecSize.tls_serialized_len.spec
  zeroizeZeroizeInst SizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (DeserializeBytesInst :
  DeserializeBytes T) (bytes : Slice Std.U8) :
  tls_vec.SecretTlsVecU24.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  zeroizeZeroizeInst DeserializeBytesInst bytes
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.tls_serialized_length.spec.proof {T : Type} (SizeInst
                                                          : Size T)
                                                          (zeroizeZeroizeInst :
                                                          zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU24 T) :
  tls_vec.SecretTlsVecU24.tls_serialized_length.spec SizeInst
  zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU24.deserialize_bytes.spec.proof {T : Type}
                                                      (DeserializeBytesInst :
                                                      DeserializeBytes T)
                                                      (zeroizeZeroizeInst :
                                                      zeroize.Zeroize T)
  (bytes : Slice Std.U8) :
  tls_vec.SecretTlsVecU24.deserialize_bytes.spec DeserializeBytesInst
  zeroizeZeroizeInst bytes
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.new.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (vec : alloc.vec.Vec T) :
  tls_vec.SecretTlsVecU32.new.spec zeroizeZeroizeInst vec
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.from_slice.spec.proof {T : Type} (zeroizeZeroizeInst
                                               : zeroize.Zeroize T)
                                               (corecloneCloneInst :
                                               core.clone.Clone T)
  (slice : Slice T) :
  tls_vec.SecretTlsVecU32.from_slice.spec zeroizeZeroizeInst corecloneCloneInst
  slice
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.len.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU32 T) :
  tls_vec.SecretTlsVecU32.len.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.is_empty.spec.proof {T : Type} (zeroizeZeroizeInst :
                                             zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU32 T) :
  tls_vec.SecretTlsVecU32.is_empty.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.into_vec.spec.proof {T : Type} (zeroizeZeroizeInst :
                                             zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU32 T) :
  tls_vec.SecretTlsVecU32.into_vec.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.push.spec.proof {T : Type} (zeroizeZeroizeInst :
                                         zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU32 T) (value : T) :
  tls_vec.SecretTlsVecU32.push.spec zeroizeZeroizeInst self value
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.pop.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU32 T) :
  tls_vec.SecretTlsVecU32.pop.spec zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.remove.spec.proof {T : Type} (zeroizeZeroizeInst :
                                           zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU32 T) (index : Std.Usize) :
  tls_vec.SecretTlsVecU32.remove.spec zeroizeZeroizeInst self index
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.get.spec.proof {T : Type} (zeroizeZeroizeInst :
                                        zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU32 T) (index : Std.Usize) :
  tls_vec.SecretTlsVecU32.get.spec zeroizeZeroizeInst self index
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.len_len.spec.proof {T : Type} (zeroizeZeroizeInst :
                                            zeroize.Zeroize T) :
  tls_vec.SecretTlsVecU32.len_len.spec zeroizeZeroizeInst
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.Insts.CoreOpsIndexIndexUsizeT.index.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU32 T) (i : Std.Usize) :
  tls_vec.SecretTlsVecU32.Insts.CoreOpsIndexIndexUsizeT.index.spec
  zeroizeZeroizeInst self i
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU32 T) (i : Std.Usize) :
  tls_vec.SecretTlsVecU32.Insts.CoreOpsIndexIndexMutUsizeT.index_mut.spec
  zeroizeZeroizeInst self i
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (SizeInst : Size T)
  (self : tls_vec.SecretTlsVecU32 T) :
  tls_vec.SecretTlsVecU32.Insts.Tls_codecSize.tls_serialized_len.spec
  zeroizeZeroizeInst SizeInst self
  := by sorry

theorem
  Shared0SecretTlsVecU32.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (SizeInst : Size T)
  (self : tls_vec.SecretTlsVecU32 T) :
  Shared0SecretTlsVecU32.Insts.Tls_codecSize.tls_serialized_len.spec
  zeroizeZeroizeInst SizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec.proof
   {T : Type} (zeroizeZeroizeInst : zeroize.Zeroize T) (DeserializeBytesInst :
  DeserializeBytes T) (bytes : Slice Std.U8) :
  tls_vec.SecretTlsVecU32.Insts.Tls_codecDeserializeBytes.tls_deserialize_bytes.spec
  zeroizeZeroizeInst DeserializeBytesInst bytes
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.tls_serialized_length.spec.proof {T : Type} (SizeInst
                                                          : Size T)
                                                          (zeroizeZeroizeInst :
                                                          zeroize.Zeroize T)
  (self : tls_vec.SecretTlsVecU32 T) :
  tls_vec.SecretTlsVecU32.tls_serialized_length.spec SizeInst
  zeroizeZeroizeInst self
  := by sorry

theorem
  tls_vec.SecretTlsVecU32.deserialize_bytes.spec.proof {T : Type}
                                                      (DeserializeBytesInst :
                                                      DeserializeBytes T)
                                                      (zeroizeZeroizeInst :
                                                      zeroize.Zeroize T)
  (bytes : Slice Std.U8) :
  tls_vec.SecretTlsVecU32.deserialize_bytes.spec DeserializeBytesInst
  zeroizeZeroizeInst bytes
  := by sorry

theorem tls_vec.TlsByteSliceU8.as_slice.spec.proof
  (self : tls_vec.TlsByteSliceU8) : tls_vec.TlsByteSliceU8.as_slice.spec self
  := by sorry

theorem tls_vec.TlsByteSliceU8.tls_serialized_byte_length.spec.proof
  (self : tls_vec.TlsByteSliceU8) :
  tls_vec.TlsByteSliceU8.tls_serialized_byte_length.spec self
  := by sorry

theorem Shared0TlsByteSliceU8.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteSliceU8) :
  Shared0TlsByteSliceU8.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  tls_vec.TlsByteSliceU8.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteSliceU8) :
  tls_vec.TlsByteSliceU8.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem tls_vec.TlsByteSliceU16.as_slice.spec.proof
  (self : tls_vec.TlsByteSliceU16) : tls_vec.TlsByteSliceU16.as_slice.spec self
  := by sorry

theorem tls_vec.TlsByteSliceU16.tls_serialized_byte_length.spec.proof
   (self : tls_vec.TlsByteSliceU16) :
  tls_vec.TlsByteSliceU16.tls_serialized_byte_length.spec self
  := by sorry

theorem
  Shared0TlsByteSliceU16.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteSliceU16) :
  Shared0TlsByteSliceU16.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  tls_vec.TlsByteSliceU16.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteSliceU16) :
  tls_vec.TlsByteSliceU16.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem tls_vec.TlsByteSliceU24.as_slice.spec.proof
  (self : tls_vec.TlsByteSliceU24) : tls_vec.TlsByteSliceU24.as_slice.spec self
  := by sorry

theorem tls_vec.TlsByteSliceU24.tls_serialized_byte_length.spec.proof
   (self : tls_vec.TlsByteSliceU24) :
  tls_vec.TlsByteSliceU24.tls_serialized_byte_length.spec self
  := by sorry

theorem
  Shared0TlsByteSliceU24.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteSliceU24) :
  Shared0TlsByteSliceU24.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  tls_vec.TlsByteSliceU24.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteSliceU24) :
  tls_vec.TlsByteSliceU24.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem tls_vec.TlsByteSliceU32.as_slice.spec.proof
  (self : tls_vec.TlsByteSliceU32) : tls_vec.TlsByteSliceU32.as_slice.spec self
  := by sorry

theorem tls_vec.TlsByteSliceU32.tls_serialized_byte_length.spec.proof
   (self : tls_vec.TlsByteSliceU32) :
  tls_vec.TlsByteSliceU32.tls_serialized_byte_length.spec self
  := by sorry

theorem
  Shared0TlsByteSliceU32.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteSliceU32) :
  Shared0TlsByteSliceU32.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem
  tls_vec.TlsByteSliceU32.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : tls_vec.TlsByteSliceU32) :
  tls_vec.TlsByteSliceU32.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

theorem tls_vec.TlsSliceU8.as_slice.spec.proof {T : Type}
  (self : tls_vec.TlsSliceU8 T) : tls_vec.TlsSliceU8.as_slice.spec self
  := by sorry

theorem
  tls_vec.TlsSliceU8.tls_serialized_length.spec.proof {T : Type} (SizeInst :
                                                     Size T)
  (self : tls_vec.TlsSliceU8 T) :
  tls_vec.TlsSliceU8.tls_serialized_length.spec SizeInst self
  := by sorry

theorem
  Shared0TlsSliceU8.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : tls_vec.TlsSliceU8 T) :
  Shared0TlsSliceU8.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsSliceU8.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : tls_vec.TlsSliceU8 T) :
  tls_vec.TlsSliceU8.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem tls_vec.TlsSliceU16.as_slice.spec.proof {T : Type}
  (self : tls_vec.TlsSliceU16 T) : tls_vec.TlsSliceU16.as_slice.spec self
  := by sorry

theorem
  tls_vec.TlsSliceU16.tls_serialized_length.spec.proof {T : Type} (SizeInst :
                                                      Size T)
  (self : tls_vec.TlsSliceU16 T) :
  tls_vec.TlsSliceU16.tls_serialized_length.spec SizeInst self
  := by sorry

theorem
  Shared0TlsSliceU16.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : tls_vec.TlsSliceU16 T) :
  Shared0TlsSliceU16.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsSliceU16.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : tls_vec.TlsSliceU16 T) :
  tls_vec.TlsSliceU16.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem tls_vec.TlsSliceU24.as_slice.spec.proof {T : Type}
  (self : tls_vec.TlsSliceU24 T) : tls_vec.TlsSliceU24.as_slice.spec self
  := by sorry

theorem
  tls_vec.TlsSliceU24.tls_serialized_length.spec.proof {T : Type} (SizeInst :
                                                      Size T)
  (self : tls_vec.TlsSliceU24 T) :
  tls_vec.TlsSliceU24.tls_serialized_length.spec SizeInst self
  := by sorry

theorem
  Shared0TlsSliceU24.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : tls_vec.TlsSliceU24 T) :
  Shared0TlsSliceU24.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsSliceU24.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : tls_vec.TlsSliceU24 T) :
  tls_vec.TlsSliceU24.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem tls_vec.TlsSliceU32.as_slice.spec.proof {T : Type}
  (self : tls_vec.TlsSliceU32 T) : tls_vec.TlsSliceU32.as_slice.spec self
  := by sorry

theorem
  tls_vec.TlsSliceU32.tls_serialized_length.spec.proof {T : Type} (SizeInst :
                                                      Size T)
  (self : tls_vec.TlsSliceU32 T) :
  tls_vec.TlsSliceU32.tls_serialized_length.spec SizeInst self
  := by sorry

theorem
  Shared0TlsSliceU32.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : tls_vec.TlsSliceU32 T) :
  Shared0TlsSliceU32.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem
  tls_vec.TlsSliceU32.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   {T : Type} (SizeInst : Size T) (self : tls_vec.TlsSliceU32 T) :
  tls_vec.TlsSliceU32.Insts.Tls_codecSize.tls_serialized_len.spec SizeInst self
  := by sorry

theorem varint.TlsVarInt.try_new.spec.proof (value : Std.U64) :
  varint.TlsVarInt.try_new.spec value
  := by sorry

theorem varint.TlsVarInt.value.spec.proof (self : varint.TlsVarInt) :
  varint.TlsVarInt.value.spec self
  := by sorry

theorem varint.TlsVarInt.bytes_len.spec.proof (self : varint.TlsVarInt) :
  varint.TlsVarInt.bytes_len.spec self
  := by sorry

theorem varint.TlsVarInt.write_bytes.spec.proof (self : varint.TlsVarInt)
  (buf : Slice Std.U8) : varint.TlsVarInt.write_bytes.spec self buf
  := by sorry

theorem varint.TlsVarInt.Insts.CoreConvertTryFromU64Error.try_from.spec.proof
   (value : Std.U64) :
  varint.TlsVarInt.Insts.CoreConvertTryFromU64Error.try_from.spec value
  := by sorry

theorem U64.Insts.CoreConvertFromTlsVarInt.from.spec.proof
  (value : varint.TlsVarInt) :
  U64.Insts.CoreConvertFromTlsVarInt.from.spec value
  := by sorry

theorem varint.TlsVarInt.Insts.Tls_codecSize.tls_serialized_len.spec.proof
   (self : varint.TlsVarInt) :
  varint.TlsVarInt.Insts.Tls_codecSize.tls_serialized_len.spec self
  := by sorry

end tls_codec
