-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [tls_codec]: type definitions
import Aeneas
import CoreModels
import TlsCodec.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace tls_codec

/-- Trait declaration: [tls_codec::Size]
    Source: 'tls_codec/src/lib.rs', lines 256:0-258:1
    Visibility: public -/
structure Size (Self : Type) where
  tls_serialized_len : Self → RustM Std.Usize

/-- Trait declaration: [tls_codec::Serialize]
    Source: 'tls_codec/src/lib.rs', lines 265:0-293:1
    Visibility: public -/
structure Serialize (Self : Type) where
  SizeInst : Size Self

/-- Trait declaration: [tls_codec::Deserialize]
    Source: 'tls_codec/src/lib.rs', lines 309:0-340:1
    Visibility: public -/
structure Deserialize (Self : Type) where
  SizeInst : Size Self

/-- [tls_codec::Error]
    Source: 'tls_codec/src/lib.rs', lines 75:0-107:1
    Visibility: public -/
@[discriminant isize]
inductive Error where
| EncodingError : alloc.string.String → Error
| InvalidVectorLength : Error
| InvalidWriteLength : alloc.string.String → Error
| InvalidInput : Error
| DecodingError : alloc.string.String → Error
| EndOfStream : Error
| TrailingData : Error
| UnknownValue : Std.U64 → Error
| LibraryError : Error

/-- [tls_codec::arrays::{impl tls_codec::DeserializeBytes for [u8; LEN]}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/arrays.rs', lines 34:22-39:83 -/
@[reducible]
def arrays.DeserializeBytesArrayU8LEN.tls_deserialize_bytes._.ensures.closure
  (LEN : Std.Usize) :=
  Slice Std.U8

/-- Trait declaration: [tls_codec::DeserializeBytes]
    Source: 'tls_codec/src/lib.rs', lines 346:0-380:1
    Visibility: public -/
structure DeserializeBytes (Self : Type) where
  SizeInst : Size Self
  tls_deserialize_bytes : Slice Std.U8 → RustM (core.result.Result (Self ×
    (Slice Std.U8)) Error)
  tls_deserialize_exact_bytes : Slice Std.U8 → RustM (core.result.Result Self
    Error)

/-- [tls_codec::arrays::{impl tls_codec::DeserializeBytes for [u8; LEN]}::tls_deserialize_bytes::closure]
    Source: 'tls_codec/src/arrays.rs', lines 47:21-47:43 -/
@[reducible]
def arrays.DeserializeBytesArrayU8LEN.tls_deserialize_bytes.closure (LEN :
  Std.Usize) :=
Unit

/-- [tls_codec::arrays::{impl tls_codec::SerializeBytes for [u8; LEN]}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/arrays.rs', lines 52:16-52:35 -/
@[reducible]
def arrays.SerializeBytesArrayU8LEN.tls_serialize_bytes._.ensures.closure (LEN
  : Std.Usize) :=
  Array Std.U8 LEN

/-- Trait declaration: [tls_codec::SerializeBytes]
    Source: 'tls_codec/src/lib.rs', lines 300:0-305:1
    Visibility: public -/
structure SerializeBytes (Self : Type) where
  SizeInst : Size Self
  tls_serialize_bytes : Self → RustM (core.result.Result (alloc.vec.Vec
    Std.U8) Error)

/-- [tls_codec::_#6::ensures::closure]
    Source: 'tls_codec/src/lib.rs', lines 299:16-299:35 -/
@[reducible]
def __6.ensures.closure (Self_ : Type) := Self_

/-- [tls_codec::_#7::ensures::closure]
    Source: 'tls_codec/src/lib.rs', lines 354:25-356:79 -/
@[reducible]
def __7.ensures.closure (Self_ : Type) := Slice Std.U8

/-- [tls_codec::_#8::ensures::closure]
    Source: 'tls_codec/src/lib.rs', lines 367:25-367:74 -/
@[reducible]
def __8.ensures.closure (Self_ : Type) := Slice Std.U8

/-- [tls_codec::U24]
    Source: 'tls_codec/src/lib.rs', lines 386:0-386:24
    Visibility: public -/
@[reducible]
def U24 := Array Std.U8 3#usize

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for core::option::Option<T>}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 50:16-50:35 -/
@[reducible]
def primitives.SerializeBytesOption.tls_serialize_bytes._.ensures.closure (T :
  Type) :=
  core.option.Option T

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for core::option::Option<T>}::tls_serialize_bytes::_::ensures::closure#1]
    Source: 'tls_codec/src/primitives.rs', lines 50:16-50:35 -/
@[reducible]
def primitives.SerializeBytesOption.tls_serialize_bytes._.ensures.closure_1 (T
  : Type) :=
  core.option.Option T

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for &'_0 core::option::Option<T>}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 80:16-80:35 -/
@[reducible]
def primitives.SerializeBytesShared0Option.tls_serialize_bytes._.ensures.closure
  (T : Type) :=
  core.option.Option T

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for core::option::Option<T>}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 113:25-117:83 -/
@[reducible]
def primitives.DeserializeBytesOption.tls_deserialize_bytes._.ensures.closure
  (T : Type) :=
  Slice Std.U8

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for u8}::tls_deserialize_bytes::closure]
    Source: 'tls_codec/src/primitives.rs', lines 167:29-167:51 -/
@[reducible]
def primitives.DeserializeBytesU8.tls_deserialize_bytes.closure := Unit

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for u16}::tls_deserialize_bytes::closure]
    Source: 'tls_codec/src/primitives.rs', lines 167:29-167:51 -/
@[reducible]
def primitives.DeserializeBytesU16.tls_deserialize_bytes.closure := Unit

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for tls_codec::U24}::tls_deserialize_bytes::closure]
    Source: 'tls_codec/src/primitives.rs', lines 167:29-167:51 -/
@[reducible]
def primitives.DeserializeBytesU24.tls_deserialize_bytes.closure := Unit

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for u32}::tls_deserialize_bytes::closure]
    Source: 'tls_codec/src/primitives.rs', lines 167:29-167:51 -/
@[reducible]
def primitives.DeserializeBytesU32.tls_deserialize_bytes.closure := Unit

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for u64}::tls_deserialize_bytes::closure]
    Source: 'tls_codec/src/primitives.rs', lines 167:29-167:51 -/
@[reducible]
def primitives.DeserializeBytesU64.tls_deserialize_bytes.closure := Unit

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for u8}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 148:68-158:71 -/
@[reducible]
def primitives.DeserializeBytesU8.tls_deserialize_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for u16}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 148:68-158:71 -/
@[reducible]
def primitives.DeserializeBytesU16.tls_deserialize_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for tls_codec::U24}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 148:68-158:71 -/
@[reducible]
def primitives.DeserializeBytesU24.tls_deserialize_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for u32}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 148:68-158:71 -/
@[reducible]
def primitives.DeserializeBytesU32.tls_deserialize_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for u64}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 148:68-158:71 -/
@[reducible]
def primitives.DeserializeBytesU64.tls_deserialize_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for &'_0 u8}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 178:46-178:64 -/
@[reducible]
def primitives.SerializeBytesShared0U8.tls_serialize_bytes._.ensures.closure :=
  Std.U8

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for &'_0 u16}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 178:46-178:64 -/
@[reducible]
def primitives.SerializeBytesShared0U16.tls_serialize_bytes._.ensures.closure
  :=
  Std.U16

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for &'_0 tls_codec::U24}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 178:46-178:64 -/
@[reducible]
def primitives.SerializeBytesShared0U24.tls_serialize_bytes._.ensures.closure
  :=
  U24

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for &'_0 u32}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 178:46-178:64 -/
@[reducible]
def primitives.SerializeBytesShared0U32.tls_serialize_bytes._.ensures.closure
  :=
  Std.U32

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for &'_0 u64}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 178:46-178:64 -/
@[reducible]
def primitives.SerializeBytesShared0U64.tls_serialize_bytes._.ensures.closure
  :=
  Std.U64

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for u8}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 188:46-188:64 -/
@[reducible]
def primitives.SerializeBytesU8.tls_serialize_bytes._.ensures.closure := Std.U8

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for u16}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 188:46-188:64 -/
@[reducible]
def primitives.SerializeBytesU16.tls_serialize_bytes._.ensures.closure :=
  Std.U16

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for tls_codec::U24}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 188:46-188:64 -/
@[reducible]
def primitives.SerializeBytesU24.tls_serialize_bytes._.ensures.closure := U24

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for u32}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 188:46-188:64 -/
@[reducible]
def primitives.SerializeBytesU32.tls_serialize_bytes._.ensures.closure :=
  Std.U32

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for u64}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 188:46-188:64 -/
@[reducible]
def primitives.SerializeBytesU64.tls_serialize_bytes._.ensures.closure :=
  Std.U64

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for (T, U)}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 265:25-267:79 -/
@[reducible]
def primitives.DeserializeBytesPair.tls_deserialize_bytes._.ensures.closure (T
  : Type) (U : Type) :=
  Slice Std.U8

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for (T, U, V)}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 327:25-329:79 -/
@[reducible]
def primitives.DeserializeBytesTupleTUV.tls_deserialize_bytes._.ensures.closure
  (T : Type) (U : Type) (V : Type) :=
  Slice Std.U8

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for ()}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 388:25-390:79 -/
@[reducible]
def primitives.DeserializeBytesTuple.tls_deserialize_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::primitives::{impl tls_codec::DeserializeBytes for core::marker::PhantomData<T>}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 424:25-426:79 -/
@[reducible]
def primitives.DeserializeBytesPhantomData.tls_deserialize_bytes._.ensures.closure
  (T : Type) :=
  Slice Std.U8

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for core::marker::PhantomData<T>}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 441:16-441:35 -/
@[reducible]
def primitives.SerializeBytesPhantomData.tls_serialize_bytes._.ensures.closure
  (T : Type) :=
  core.marker.PhantomData T

/-- [tls_codec::primitives::{impl tls_codec::SerializeBytes for alloc::boxed::Box<T>}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/primitives.rs', lines 468:16-468:35 -/
@[reducible]
def primitives.SerializeBytesBox.tls_serialize_bytes._.ensures.closure (T :
  Type) :=
  T

/-- [tls_codec::varint::TlsVarInt]
    Source: 'tls_codec/src/varint.rs', lines 7:0-7:26
    Visibility: public -/
@[reducible]
def varint.TlsVarInt := Std.U64

/-- [tls_codec::quic_vec::ContentLength]
    Source: 'tls_codec/src/quic_vec.rs', lines 43:0-43:39 -/
@[reducible]
def quic_vec.ContentLength := varint.TlsVarInt

/-- [tls_codec::quic_vec::{tls_codec::quic_vec::ContentLength}::from_usize::_::ensures::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 63:22-63:55 -/
@[reducible]
def quic_vec.ContentLength.from_usize._.ensures.closure := Std.Usize

/-- [tls_codec::quic_vec::{impl tls_codec::DeserializeBytes for tls_codec::quic_vec::ContentLength}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 80:25-82:79 -/
@[reducible]
def quic_vec.DeserializeBytesContentLength.tls_deserialize_bytes._.ensures.closure
  :=
  Slice Std.U8

/-- [tls_codec::varint::{impl tls_codec::DeserializeBytes for tls_codec::varint::TlsVarInt}::tls_deserialize_bytes::closure]
    Source: 'tls_codec/src/varint.rs', lines 173:54-173:77 -/
@[reducible]
def varint.DeserializeBytesTlsVarInt.tls_deserialize_bytes.closure := Unit

/-- [tls_codec::quic_vec::{impl tls_codec::Size for &'_0 [T]}::tls_serialized_len::closure#1]
    Source: 'tls_codec/src/quic_vec.rs', lines 276:17-276:62 -/
@[reducible]
def quic_vec.SizeShared0Slice.tls_serialized_len.closure_1 (T : Type) := Unit

/-- [tls_codec::quic_vec::{impl tls_codec::Size for &'_0 [T]}::tls_serialized_len::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 274:21-274:73 -/
@[reducible]
def quic_vec.SizeShared0Slice.tls_serialized_len.closure (T : Type) := Unit

/-- [tls_codec::quic_vec::{impl tls_codec::DeserializeBytes for alloc::vec::Vec<T>}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 110:25-112:79 -/
@[reducible]
def quic_vec.DeserializeBytesVec.tls_deserialize_bytes._.ensures.closure (T :
  Type) :=
  Slice Std.U8

/-- [tls_codec::quic_vec::VLBytes]
    Source: 'tls_codec/src/quic_vec.rs', lines 375:0-377:1
    Visibility: public -/
structure quic_vec.VLBytes where
  vec : alloc.vec.Vec Std.U8

/-- [tls_codec::quic_vec::{impl tls_codec::SerializeBytes for tls_codec::quic_vec::VLBytes}::tls_serialize_bytes::_::ensures::closure#1]
    Source: 'tls_codec/src/quic_vec.rs', lines 164:16-164:35 -/
@[reducible]
def quic_vec.SerializeBytesVLBytes.tls_serialize_bytes._.ensures.closure_1 :=
  quic_vec.VLBytes

/-- [tls_codec::quic_vec::tls_serialize_bytes_len::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 414:13-414:58 -/
@[reducible]
def quic_vec.tls_serialize_bytes_len.closure := Unit

/-- [tls_codec::quic_vec::{impl tls_codec::SerializeBytes for tls_codec::quic_vec::VLBytes}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 167:70-168:85 -/
@[reducible]
def quic_vec.SerializeBytesVLBytes.tls_serialize_bytes._.ensures.closure :=
  quic_vec.VLBytes

/-- [tls_codec::quic_vec::{impl tls_codec::SerializeBytes for &'_0 tls_codec::quic_vec::VLBytes}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 196:16-196:35 -/
@[reducible]
def quic_vec.SerializeBytesShared0VLBytes.tls_serialize_bytes._.ensures.closure
  :=
  quic_vec.VLBytes

/-- [tls_codec::quic_vec::{impl tls_codec::SerializeBytes for &'_0 alloc::vec::Vec<T>}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 248:16-248:35 -/
@[reducible]
def quic_vec.SerializeBytesShared0Vec.tls_serialize_bytes._.ensures.closure (T
  : Type) :=
  alloc.vec.Vec T

/-- [tls_codec::quic_vec::{impl tls_codec::SerializeBytes for alloc::vec::Vec<T>}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 258:16-258:35 -/
@[reducible]
def quic_vec.SerializeBytesVec.tls_serialize_bytes._.ensures.closure (T : Type)
  :=
  alloc.vec.Vec T

/-- [tls_codec::quic_vec::VLByteVec]
    Source: 'tls_codec/src/quic_vec.rs', lines 492:0-499:1
    Visibility: public -/
structure quic_vec.VLByteVec where
  vec : alloc.vec.Vec Std.U8

/-- [tls_codec::quic_vec::{impl tls_codec::DeserializeBytes for tls_codec::quic_vec::VLBytes}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 435:25-437:79 -/
@[reducible]
def quic_vec.DeserializeBytesVLBytes.tls_deserialize_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::quic_vec::{impl tls_codec::DeserializeBytes for tls_codec::quic_vec::VLByteVec}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 543:25-545:79 -/
@[reducible]
def quic_vec.DeserializeBytesVLByteVec.tls_deserialize_bytes._.ensures.closure
  :=
  Slice Std.U8

/-- [tls_codec::quic_vec::VLByteSlice]
    Source: 'tls_codec/src/quic_vec.rs', lines 661:0-661:41
    Visibility: public -/
@[reducible]
def quic_vec.VLByteSlice := Slice Std.U8

/-- [tls_codec::quic_vec::{impl tls_codec::SerializeBytes for tls_codec::quic_vec::ContentLength}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 699:16-699:35 -/
@[reducible]
def quic_vec.SerializeBytesContentLength.tls_serialize_bytes._.ensures.closure
  :=
  quic_vec.ContentLength

/-- [tls_codec::quic_vec::{impl tls_codec::SerializeBytes for tls_codec::quic_vec::VLByteSlice<'_0>}::tls_serialize_bytes::_::ensures::closure#1]
    Source: 'tls_codec/src/quic_vec.rs', lines 708:16-708:35 -/
@[reducible]
def quic_vec.SerializeBytesVLByteSlice.tls_serialize_bytes._.ensures.closure_1
  :=
  quic_vec.VLByteSlice

/-- [tls_codec::quic_vec::{impl tls_codec::SerializeBytes for tls_codec::quic_vec::VLByteSlice<'_0>}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/quic_vec.rs', lines 711:61-712:76 -/
@[reducible]
def quic_vec.SerializeBytesVLByteSlice.tls_serialize_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::spec::_::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec._.ensures.closure := Std.U8

/-- [tls_codec::spec::_#2::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__2.ensures.closure := Std.U16

/-- [tls_codec::spec::_#4::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__4.ensures.closure := Std.U32

/-- [tls_codec::spec::_#6::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__6.ensures.closure := Std.U64

/-- [tls_codec::spec::_#8::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__8.ensures.closure := U24

/-- [tls_codec::spec::_#10::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__10.ensures.closure := Array Std.U8 4#usize

/-- [tls_codec::spec::_#12::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__12.ensures.closure := core.option.Option Std.U16

/-- [tls_codec::spec::_#17::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__17.ensures.closure := quic_vec.VLBytes

/-- [tls_codec::tls_vec::TlsByteVecU8]
    Source: 'tls_codec/src/tls_vec.rs', lines 755:8-757:9
    Visibility: public -/
structure tls_vec.TlsByteVecU8 where
  vec : alloc.vec.Vec Std.U8

/-- [tls_codec::spec::_#19::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__19.ensures.closure := tls_vec.TlsByteVecU8

/-- [tls_codec::tls_vec::TlsByteVecU16]
    Source: 'tls_codec/src/tls_vec.rs', lines 755:8-757:9
    Visibility: public -/
structure tls_vec.TlsByteVecU16 where
  vec : alloc.vec.Vec Std.U8

/-- [tls_codec::spec::_#21::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__21.ensures.closure := tls_vec.TlsByteVecU16

/-- [tls_codec::tls_vec::TlsByteVecU24]
    Source: 'tls_codec/src/tls_vec.rs', lines 755:8-757:9
    Visibility: public -/
structure tls_vec.TlsByteVecU24 where
  vec : alloc.vec.Vec Std.U8

/-- [tls_codec::spec::_#23::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__23.ensures.closure := tls_vec.TlsByteVecU24

/-- [tls_codec::tls_vec::TlsByteVecU32]
    Source: 'tls_codec/src/tls_vec.rs', lines 755:8-757:9
    Visibility: public -/
structure tls_vec.TlsByteVecU32 where
  vec : alloc.vec.Vec Std.U8

/-- [tls_codec::spec::_#25::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__25.ensures.closure := tls_vec.TlsByteVecU32

/-- [tls_codec::spec::_#27::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__27.ensures.closure := alloc.vec.Vec Std.U16

/-- [tls_codec::spec::_#29::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 17:29-17:79 -/
@[reducible]
def spec.__29.ensures.closure := alloc.string.String

/-- [tls_codec::string::{impl tls_codec::DeserializeBytes for alloc::string::String}::tls_deserialize_bytes::closure]
    Source: 'tls_codec/src/string.rs', lines 75:21-75:86 -/
@[reducible]
def string.DeserializeBytesString.tls_deserialize_bytes.closure := Unit

/-- [tls_codec::spec::_#15::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 30:29-30:80 -/
@[reducible]
def spec.__15.ensures.closure := varint.TlsVarInt

/-- [tls_codec::spec::_#1::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__1.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#3::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__3.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#5::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__5.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#7::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__7.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#9::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__9.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#11::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__11.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#13::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__13.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#16::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__16.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#18::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__18.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#20::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__20.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#22::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__22.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#24::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__24.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#26::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__26.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#28::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__28.ensures.closure := Slice Std.U8

/-- [tls_codec::spec::_#30::ensures::closure]
    Source: 'tls_codec/src/spec.rs', lines 42:29-42:92 -/
@[reducible]
def spec.__30.ensures.closure := Slice Std.U8

/-- [tls_codec::string::{impl tls_codec::SerializeBytes for alloc::string::String}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/string.rs', lines 32:16-32:35 -/
@[reducible]
def string.SerializeBytesString.tls_serialize_bytes._.ensures.closure :=
  alloc.string.String

/-- [tls_codec::string::{impl tls_codec::SerializeBytes for str}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/string.rs', lines 41:16-41:35 -/
@[reducible]
def string.SerializeBytesStr.tls_serialize_bytes._.ensures.closure := Str

/-- [tls_codec::string::{impl tls_codec::SerializeBytes for &'_0 str}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/string.rs', lines 50:16-50:35 -/
@[reducible]
def string.SerializeBytesShared0Str.tls_serialize_bytes._.ensures.closure :=
  Str

/-- [tls_codec::string::{impl tls_codec::DeserializeBytes for alloc::string::String}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/string.rs', lines 62:25-68:83 -/
@[reducible]
def string.DeserializeBytesString.tls_deserialize_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::string::{impl tls_codec::DeserializeBytes for alloc::string::String}::tls_deserialize_bytes::_::ensures::closure::closure]
    Source: 'tls_codec/src/string.rs', lines 63:62-65:61 -/
def string.DeserializeBytesString.tls_deserialize_bytes._.ensures.closure.closure
  :=
  alloc.string.String × Slice Std.U8

/-- [tls_codec::tls_vec::TlsVecU8]
    Source: 'tls_codec/src/tls_vec.rs', lines 549:8-551:9
    Visibility: public -/
structure tls_vec.TlsVecU8 (T : Type) where
  vec : alloc.vec.Vec T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsVecU8<T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.TlsVecU8.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::TlsVecU16]
    Source: 'tls_codec/src/tls_vec.rs', lines 549:8-551:9
    Visibility: public -/
structure tls_vec.TlsVecU16 (T : Type) where
  vec : alloc.vec.Vec T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsVecU16<T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.TlsVecU16.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::TlsVecU24]
    Source: 'tls_codec/src/tls_vec.rs', lines 549:8-551:9
    Visibility: public -/
structure tls_vec.TlsVecU24 (T : Type) where
  vec : alloc.vec.Vec T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsVecU24<T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.TlsVecU24.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::TlsVecU32]
    Source: 'tls_codec/src/tls_vec.rs', lines 549:8-551:9
    Visibility: public -/
structure tls_vec.TlsVecU32 (T : Type) where
  vec : alloc.vec.Vec T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsVecU32<T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.TlsVecU32.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::SecretTlsVecU8]
    Source: 'tls_codec/src/tls_vec.rs', lines 549:8-551:9
    Visibility: public -/
structure tls_vec.SecretTlsVecU8 (T : Type) where
  vec : alloc.vec.Vec T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::SecretTlsVecU8<T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.SecretTlsVecU8.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::SecretTlsVecU16]
    Source: 'tls_codec/src/tls_vec.rs', lines 549:8-551:9
    Visibility: public -/
structure tls_vec.SecretTlsVecU16 (T : Type) where
  vec : alloc.vec.Vec T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::SecretTlsVecU16<T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.SecretTlsVecU16.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::SecretTlsVecU24]
    Source: 'tls_codec/src/tls_vec.rs', lines 549:8-551:9
    Visibility: public -/
structure tls_vec.SecretTlsVecU24 (T : Type) where
  vec : alloc.vec.Vec T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::SecretTlsVecU24<T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.SecretTlsVecU24.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::SecretTlsVecU32]
    Source: 'tls_codec/src/tls_vec.rs', lines 549:8-551:9
    Visibility: public -/
structure tls_vec.SecretTlsVecU32 (T : Type) where
  vec : alloc.vec.Vec T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::SecretTlsVecU32<T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.SecretTlsVecU32.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::TlsSliceU8]
    Source: 'tls_codec/src/tls_vec.rs', lines 1077:8-1077:45
    Visibility: public -/
@[reducible]
def tls_vec.TlsSliceU8 (T : Type) := Slice T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsSliceU8<'a, T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.TlsSliceU8.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::TlsSliceU16]
    Source: 'tls_codec/src/tls_vec.rs', lines 1077:8-1077:45
    Visibility: public -/
@[reducible]
def tls_vec.TlsSliceU16 (T : Type) := Slice T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsSliceU16<'a, T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.TlsSliceU16.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::TlsSliceU24]
    Source: 'tls_codec/src/tls_vec.rs', lines 1077:8-1077:45
    Visibility: public -/
@[reducible]
def tls_vec.TlsSliceU24 (T : Type) := Slice T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsSliceU24<'a, T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.TlsSliceU24.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::TlsSliceU32]
    Source: 'tls_codec/src/tls_vec.rs', lines 1077:8-1077:45
    Visibility: public -/
@[reducible]
def tls_vec.TlsSliceU32 (T : Type) := Slice T

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsSliceU32<'a, T>}::tls_serialized_length::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 28:36-28:88 -/
@[reducible]
def tls_vec.TlsSliceU32.tls_serialized_length.closure (T : Type) := Unit

/-- [tls_codec::tls_vec::TlsByteSliceU8]
    Source: 'tls_codec/src/tls_vec.rs', lines 1020:8-1020:43
    Visibility: public -/
@[reducible]
def tls_vec.TlsByteSliceU8 := Slice Std.U8

/-- [tls_codec::tls_vec::TlsByteSliceU16]
    Source: 'tls_codec/src/tls_vec.rs', lines 1020:8-1020:43
    Visibility: public -/
@[reducible]
def tls_vec.TlsByteSliceU16 := Slice Std.U8

/-- [tls_codec::tls_vec::TlsByteSliceU24]
    Source: 'tls_codec/src/tls_vec.rs', lines 1020:8-1020:43
    Visibility: public -/
@[reducible]
def tls_vec.TlsByteSliceU24 := Slice Std.U8

/-- [tls_codec::tls_vec::TlsByteSliceU32]
    Source: 'tls_codec/src/tls_vec.rs', lines 1020:8-1020:43
    Visibility: public -/
@[reducible]
def tls_vec.TlsByteSliceU32 := Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU8}::deserialize_bytes_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 74:33-75:73 -/
@[reducible]
def tls_vec.TlsByteVecU8.deserialize_bytes_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU16}::deserialize_bytes_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 74:33-75:73 -/
@[reducible]
def tls_vec.TlsByteVecU16.deserialize_bytes_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU24}::deserialize_bytes_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 74:33-75:73 -/
@[reducible]
def tls_vec.TlsByteVecU24.deserialize_bytes_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU32}::deserialize_bytes_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 74:33-75:73 -/
@[reducible]
def tls_vec.TlsByteVecU32.deserialize_bytes_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsVecU8<T>}::deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 143:33-144:77 -/
@[reducible]
def tls_vec.TlsVecU8.deserialize_bytes._.ensures.closure (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsVecU16<T>}::deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 143:33-144:77 -/
@[reducible]
def tls_vec.TlsVecU16.deserialize_bytes._.ensures.closure (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsVecU24<T>}::deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 143:33-144:77 -/
@[reducible]
def tls_vec.TlsVecU24.deserialize_bytes._.ensures.closure (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsVecU32<T>}::deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 143:33-144:77 -/
@[reducible]
def tls_vec.TlsVecU32.deserialize_bytes._.ensures.closure (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::SecretTlsVecU8<T>}::deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 143:33-144:77 -/
@[reducible]
def tls_vec.SecretTlsVecU8.deserialize_bytes._.ensures.closure (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::SecretTlsVecU16<T>}::deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 143:33-144:77 -/
@[reducible]
def tls_vec.SecretTlsVecU16.deserialize_bytes._.ensures.closure (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::SecretTlsVecU24<T>}::deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 143:33-144:77 -/
@[reducible]
def tls_vec.SecretTlsVecU24.deserialize_bytes._.ensures.closure (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::SecretTlsVecU32<T>}::deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 143:33-144:77 -/
@[reducible]
def tls_vec.SecretTlsVecU32.deserialize_bytes._.ensures.closure (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU8}::serialize_bytes_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 301:33-301:51 -/
@[reducible]
def tls_vec.TlsByteVecU8.serialize_bytes_bytes._.ensures.closure :=
  tls_vec.TlsByteVecU8

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU16}::serialize_bytes_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 301:33-301:51 -/
@[reducible]
def tls_vec.TlsByteVecU16.serialize_bytes_bytes._.ensures.closure :=
  tls_vec.TlsByteVecU16

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU24}::serialize_bytes_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 301:33-301:51 -/
@[reducible]
def tls_vec.TlsByteVecU24.serialize_bytes_bytes._.ensures.closure :=
  tls_vec.TlsByteVecU24

/-- [tls_codec::tls_vec::{tls_codec::tls_vec::TlsByteVecU32}::serialize_bytes_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 301:33-301:51 -/
@[reducible]
def tls_vec.TlsByteVecU32.serialize_bytes_bytes._.ensures.closure :=
  tls_vec.TlsByteVecU32

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::TlsVecU8<T>}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 366:33-368:87 -/
@[reducible]
def tls_vec.DeserializeBytesTlsVecU8.tls_deserialize_bytes._.ensures.closure (T
  : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::TlsVecU16<T>}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 366:33-368:87 -/
@[reducible]
def tls_vec.DeserializeBytesTlsVecU16.tls_deserialize_bytes._.ensures.closure
  (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::TlsVecU24<T>}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 366:33-368:87 -/
@[reducible]
def tls_vec.DeserializeBytesTlsVecU24.tls_deserialize_bytes._.ensures.closure
  (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::TlsVecU32<T>}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 366:33-368:87 -/
@[reducible]
def tls_vec.DeserializeBytesTlsVecU32.tls_deserialize_bytes._.ensures.closure
  (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::SecretTlsVecU8<T>}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 366:33-368:87 -/
@[reducible]
def tls_vec.DeserializeBytesSecretTlsVecU8.tls_deserialize_bytes._.ensures.closure
  (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::SecretTlsVecU16<T>}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 366:33-368:87 -/
@[reducible]
def tls_vec.DeserializeBytesSecretTlsVecU16.tls_deserialize_bytes._.ensures.closure
  (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::SecretTlsVecU24<T>}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 366:33-368:87 -/
@[reducible]
def tls_vec.DeserializeBytesSecretTlsVecU24.tls_deserialize_bytes._.ensures.closure
  (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::SecretTlsVecU32<T>}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 366:33-368:87 -/
@[reducible]
def tls_vec.DeserializeBytesSecretTlsVecU32.tls_deserialize_bytes._.ensures.closure
  (T : Type) :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::TlsByteVecU8}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 420:33-422:87 -/
@[reducible]
def tls_vec.DeserializeBytesTlsByteVecU8.tls_deserialize_bytes._.ensures.closure
  :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::TlsByteVecU16}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 420:33-422:87 -/
@[reducible]
def tls_vec.DeserializeBytesTlsByteVecU16.tls_deserialize_bytes._.ensures.closure
  :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::TlsByteVecU24}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 420:33-422:87 -/
@[reducible]
def tls_vec.DeserializeBytesTlsByteVecU24.tls_deserialize_bytes._.ensures.closure
  :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::DeserializeBytes for tls_codec::tls_vec::TlsByteVecU32}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 420:33-422:87 -/
@[reducible]
def tls_vec.DeserializeBytesTlsByteVecU32.tls_deserialize_bytes._.ensures.closure
  :=
  Slice Std.U8

/-- [tls_codec::tls_vec::{impl tls_codec::SerializeBytes for tls_codec::tls_vec::TlsByteVecU8}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 431:46-431:64 -/
@[reducible]
def tls_vec.SerializeBytesTlsByteVecU8.tls_serialize_bytes._.ensures.closure :=
  tls_vec.TlsByteVecU8

/-- [tls_codec::tls_vec::{impl tls_codec::SerializeBytes for tls_codec::tls_vec::TlsByteVecU16}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 431:46-431:64 -/
@[reducible]
def tls_vec.SerializeBytesTlsByteVecU16.tls_serialize_bytes._.ensures.closure
  :=
  tls_vec.TlsByteVecU16

/-- [tls_codec::tls_vec::{impl tls_codec::SerializeBytes for tls_codec::tls_vec::TlsByteVecU24}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 431:46-431:64 -/
@[reducible]
def tls_vec.SerializeBytesTlsByteVecU24.tls_serialize_bytes._.ensures.closure
  :=
  tls_vec.TlsByteVecU24

/-- [tls_codec::tls_vec::{impl tls_codec::SerializeBytes for tls_codec::tls_vec::TlsByteVecU32}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/tls_vec.rs', lines 431:46-431:64 -/
@[reducible]
def tls_vec.SerializeBytesTlsByteVecU32.tls_serialize_bytes._.ensures.closure
  :=
  tls_vec.TlsByteVecU32

/-- [tls_codec::varint::{impl tls_codec::DeserializeBytes for tls_codec::varint::TlsVarInt}::tls_deserialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/varint.rs', lines 161:25-164:79 -/
@[reducible]
def varint.DeserializeBytesTlsVarInt.tls_deserialize_bytes._.ensures.closure :=
  Slice Std.U8

/-- [tls_codec::varint::{impl tls_codec::SerializeBytes for tls_codec::varint::TlsVarInt}::tls_serialize_bytes::_::ensures::closure]
    Source: 'tls_codec/src/varint.rs', lines 211:16-211:35 -/
@[reducible]
def varint.SerializeBytesTlsVarInt.tls_serialize_bytes._.ensures.closure :=
  varint.TlsVarInt

end tls_codec
